<?php
/**
 * Built-in language presets for the cookie consent banner.
 *
 * @package CookieConsentWPS
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class CCWPS_Language_Presets {

	/**
	 * Returns all available language presets.
	 * Keys map directly to option names (without ccwps_ prefix).
	 */
	public static function get_all(): array {
		return [
			'en' => [
				'label'     => 'English',
				'flag'      => '🇬🇧',
				'flag_file' => 'GB',
				'admin_strings' => [
					// Sidebar nav
					'admin_lang_label'              => 'Language:',
					'admin_nav_settings'            => 'Settings',
					'admin_nav_appearance'          => 'Appearance',
					'admin_nav_translations'        => 'Translations',
					'admin_nav_cookies'             => 'Cookies',
					'admin_nav_blocking'            => 'Script Blocking',
					'admin_nav_log'                 => 'Consent Log',
					'admin_nav_shortcodes'          => 'Shortcodes',
					'admin_nav_tools'               => 'Tools',
					'admin_nav_about'               => 'About Plugin',
					'admin_preview_banner'          => 'Show banner',
					'admin_preview_modal'           => 'Cookie settings',
					'admin_preview_label'           => 'Preview:',
					// Tab h1 titles
					'admin_tab_settings_h1'         => 'Behaviour Settings',
					'admin_tab_appearance_h1'       => 'Banner Appearance',
					'admin_tab_translations_h1'     => 'Frontend Translations',
					'admin_tab_cookies_h1'          => 'Cookie Declaration',
					'admin_tab_blocking_h1'         => 'Script Blocking',
					'admin_tab_log_h1'              => 'Consent Log',
					'admin_tab_tools_h1'            => 'Tools',
					// Section h2 titles
					'admin_sect_banner_behavior'    => 'Banner Behaviour',
					'admin_sect_cookie_settings'    => 'Cookie Consent Settings',
					'admin_sect_layout'             => 'Banner Layout & Position',
					'admin_sect_floating_icon'      => 'Floating Icon',
					'admin_sect_typography'         => 'Typography & Border Radius',
					'admin_sect_lang_presets'       => 'Quick Language Presets',
					'admin_sect_export'             => 'Export Settings',
					'admin_sect_import'             => 'Import Settings',
					'admin_sect_reset'              => 'Reset to Defaults',
					'admin_sect_plugin_info'        => 'Plugin Information',
					// Buttons
					'admin_btn_save_settings'       => 'Save Settings',
					'admin_btn_save_appearance'     => 'Save Appearance',
					'admin_btn_save_translations'   => 'Save Translations',
					'admin_btn_add_cookie'          => 'Add Cookie',
					'admin_btn_add_rule'            => 'Add Rule',
					'admin_btn_edit'                => 'Edit',
					'admin_btn_delete'              => 'Delete',
					'admin_btn_cancel'              => 'Cancel',
					'admin_btn_save'                => 'Save',
					'admin_btn_copy'                => 'Copy',
					'admin_btn_export_csv'          => 'Export CSV',
					'admin_btn_clear_log'           => 'Clear All Records',
					'admin_btn_export_json'         => 'Download settings.json',
					'admin_btn_import_json'         => 'Import Settings',
					'admin_btn_reset'               => 'Reset Settings',
					'admin_btn_remove'              => 'Remove',
					'admin_btn_show_list'           => 'Show List',
					// Table columns
					'admin_tip_label'               => 'Tip / Help',
					'admin_col_name'                => 'Name',
					'admin_col_domain'              => 'Domain',
					'admin_col_expiry'              => 'Expiry',
					'admin_col_description'         => 'Description',
					'admin_col_category'            => 'Category',
					'admin_col_actions'             => 'Actions',
					'admin_col_script_source'       => 'Script Source',
					'admin_col_date'                => 'Date',
					'admin_col_consent_id'          => 'Consent ID',
					'admin_col_ip'                  => 'IP Address',
					'admin_col_updated'             => 'Updated',
					// Translations tab — section names
					'admin_trans_sect_modal'        => 'Preferences Modal',
					'admin_trans_sect_cookie_table' => 'Cookie Table',
					'admin_trans_sect_categories'   => 'Cookie Categories',
					// Translations tab — field labels
					'admin_trans_banner_title'      => 'Banner Title',
					'admin_trans_banner_desc'       => 'Banner Description',
					'admin_trans_accept_all'        => 'Button "Accept All"',
					'admin_trans_reject_all'        => 'Button "Reject All"',
					'admin_trans_manage_pref'       => 'Button "Customize"',
					'admin_trans_powered_by'        => '"Powered by" link text',
					'admin_trans_save_pref'         => 'Button "Save Preferences"',
					'admin_trans_close'             => 'Button "Close"',
					'admin_trans_consent_id'        => 'Consent ID Label',
					'admin_trans_always_on'         => '"Always On" label',
					'admin_trans_col_name'          => 'Column: Name',
					'admin_trans_col_domain'        => 'Column: Domain',
					'admin_trans_col_expiry'        => 'Column: Expiry',
					'admin_trans_col_desc'          => 'Column: Description',
					'admin_trans_necessary_title'   => 'Necessary – Title',
					'admin_trans_necessary_desc'    => 'Necessary – Description',
					'admin_trans_analytics_title'   => 'Analytics – Title',
					'admin_trans_analytics_desc'    => 'Analytics – Description',
					'admin_trans_targeting_title'   => 'Targeting – Title',
					'admin_trans_targeting_desc'    => 'Targeting – Description',
					'admin_trans_preferences_title' => 'Preferences – Title',
					'admin_trans_preferences_desc'  => 'Preferences – Description',
				],
				'admin_texts' => [
					'Funguje na základe' => 'Powered by',
					'Bezplatný plugin vytvoril:' => 'Free plugin by:',
					'Automatické spustenie' => 'Automatic launch',
					'Banner sa zobrazí automaticky pri načítaní stránky.' => 'The banner is shown automatically when the page loads.',
					'Vynútený súhlas' => 'Forced consent',
					'Používateľ nemôže prehliadať web bez udelenia súhlasu.' => 'Users cannot browse the website without giving consent.',
					'Automatické vymazanie cookies' => 'Automatic cookie deletion',
					'Pri odvolaní súhlasu sa automaticky vymažú cookies danej kategórie.' => 'When consent is withdrawn, cookies in the given category are deleted automatically.',
					'Správa skriptov na stránke' => 'Script management on page',
					'Blokuje skripty tretích strán, kým používateľ neudelí súhlas.' => 'Blocks third-party scripts until the user grants consent.',
					'Skryť pre robotov' => 'Hide from bots',
					'Banner sa nezobrazí vyhľadávačom a crawlerom.' => 'The banner is hidden for search engines and crawlers.',
					'Opätovný súhlas' => 'Re-consent',
					'Zobrazí banner znova, keď sa zmení zoznam cookies.' => 'Shows the banner again when the cookie list changes.',
					'Zaznamenávať súhlasy' => 'Record consents',
					'Každý súhlas sa uloží do databázy (ID, IP, URL, čas).' => 'Each consent is stored in the database (ID, IP, URL, time).',
					'Skryť prázdne kategórie' => 'Hide empty categories',
					'V modáli preferencií sa skryjú kategórie bez deklarovaných cookies.' => 'In the preferences modal, categories without declared cookies are hidden.',
					'Oneskorenie zobrazenia (ms)' => 'Display delay (ms)',
					'Čas v milisekundách pred zobrazením bannera.' => 'Time in milliseconds before showing the banner.',
					'Platnosť súhlasu (dni)' => 'Consent validity (days)',
					'Po koľkých dňoch vyprší súhlas a banner sa zobrazí znova.' => 'After how many days consent expires and the banner is shown again.',
					'Cesta cookie' => 'Cookie path',
					'Cesta, na ktorej bude cookie platná.' => 'Path where the cookie is valid.',
					'Doména cookie' => 'Cookie domain',
					'Nechajte prázdne pre automatickú detekciu.' => 'Leave empty for automatic detection.',
					'Čo je Consent Mode?' => 'What is Consent Mode?',
					' Google Consent Mode umožňuje Googlu modelovať chýbajúce dáta, keď používatelia odmietnu analytické/reklamné cookies. Vaše kampane budú stále merateľné aj bez plného súhlasu.' => ' Google Consent Mode lets Google model missing data when users reject analytics/advertising cookies. Your campaigns can still be measurable even without full consent.',
					'Google Consent Mode umožňuje Googlu modelovať chýbajúce dáta, keď používatelia odmietnu analytické/reklamné cookies. Vaše kampane budú stále merateľné aj bez plného súhlasu.' => 'Google Consent Mode lets Google model missing data when users reject analytics/advertising cookies. Your campaigns can still be measurable even without full consent.',
					'Verzia Consent Mode' => 'Consent Mode version',
					'Vypnuté' => 'Disabled',
					'Consent Mode sa nepoužíva. Vhodné ak nepoužívate Google Analytics ani Ads.' => 'Consent Mode is not used. Suitable if you do not use Google Analytics or Ads.',
					'Štandard od marca 2024. Vyžadovaný pre Google Ads a GA4 v EÚ. Posiela signály ad_user_data a ad_personalization. Nutné pre remarketing a konverzie.' => 'Standard since March 2024. Required for Google Ads and GA4 in the EU. Sends ad_user_data and ad_personalization signals. Needed for remarketing and conversions.',
					'Rozšírenie v2 o developer ID signál. Zahŕňa všetky funkcie v2 + nastavenie developer_id pre presnejšie modelovanie konverzií. Vhodné pre pokročilé Google Marketing Platform funkcie.' => 'Extension of v2 with a developer ID signal. Includes all v2 features plus developer_id for more accurate conversion modeling. Suitable for advanced Google Marketing Platform use cases.',
					'Odporúčané' => 'Recommended',
					'Nové' => 'New',
					'Voliteľné: Plugin načíta GTM automaticky.' => 'Optional: the plugin loads GTM automatically.',
					'💡 Vyplňte len ak GTM nenačítavate iným spôsobom. Ak GTM máte v téme alebo inom plugine, nechajte prázdne.' => '💡 Fill this only if GTM is not loaded another way. If GTM is already loaded by your theme or another plugin, leave it empty.',
					'💡 Hodnota 0 = okamžite. Odporúčame 0–500 ms. Vyššie hodnoty môžu byť problém pri GDPR auditoch.' => '💡 Value 0 = immediate. We recommend 0–500 ms. Higher values can be problematic in GDPR audits.',
					'💡 GDPR odporúča max. 13 mesiacov (390 dní). Predvolených 182 dní (6 mes.) je bezpečná hodnota.' => '💡 GDPR recommends max. 13 months (390 days). The default 182 days (6 months) is a safe value.',
					'💡 Nechajte "/" – cookie bude platná na celom webe.' => '💡 Keep "/" so the cookie is valid across the whole site.',
					'💡 Vyplňte ".mojeweb.sk" (s bodkou) ak chcete zdieľať súhlas medzi subdoménami.' => '💡 Use ".example.com" (with a leading dot) to share consent across subdomains.',
					'💡 Pre väčšinu webov stačí v2. v3 použite ak využívate pokročilé Google Marketing Platform funkcie. Obe verzie vyžadujú GTM alebo manuálne načítanie gtag.js.' => '💡 v2 is enough for most websites. Use v3 if you use advanced Google Marketing Platform features. Both versions require GTM or manual gtag.js loading.',
					'💡 Odporúčame zapnúť. Vypnuté = zobraziť manuálne cez <code>CookieConsentWPS.showBanner()</code>' => '💡 We recommend enabling this. Disabled = show manually via <code>CookieConsentWPS.showBanner()</code>.',
					'⚠️ GDPR neukladá povinnosť vynútiť súhlas. Odporúčame VYPNÚŤ – používateľ má právo odmietnuť.' => '⚠️ GDPR does not require forced consent. We recommend DISABLING it because users have the right to refuse.',
					'💡 Funguje len pre cookies deklarované v záložke Cookies. Odporúčame zapnúť.' => '💡 Works only for cookies declared in the Cookies tab. We recommend enabling it.',
					'💡 Definujte pravidlá v záložke "Blokovanie skriptov". Plugin zmení typ skriptu na text/plain.' => '💡 Define rules in the "Script Blocking" tab. The plugin changes script type to text/plain.',
					'💡 Odporúčame zapnúť. Zlepšuje SEO skóre webu.' => '💡 We recommend enabling this. It improves SEO score.',
					'💡 Odporúčame zapnúť – GDPR vyžaduje nový súhlas po zmene účelu spracovania.' => '💡 We recommend enabling this. GDPR requires renewed consent after purpose changes.',
					'💡 Odporúčame zapnúť – záznamy slúžia ako dôkaz súhlasu pre GDPR audit.' => '💡 We recommend enabling this. Records serve as proof of consent for GDPR audits.',
					'💡 Zapnite, keď máte vyplnené všetky kategórie v záložke Cookies.' => '💡 Enable this when all categories are filled in the Cookies tab.',
					'O plugine Advanced Cookie Consent for EU' => 'About Advanced Cookie Consent for EU',
					'Popis pluginu' => 'Plugin description',
					'Hlavné funkcie' => 'Main features',
					'Postup nastavenia' => 'Setup steps',
					'Nastavenie Google Tag Manager + Consent Mode' => 'Google Tag Manager + Consent Mode setup',
					'Autor a podpora' => 'Author and support',
					'Typ bannera' => 'Banner type',
					'Poloha bannera' => 'Banner position',
					'Dole vľavo' => 'Bottom left',
					'Dole vpravo' => 'Bottom right',
					'Dole v strede' => 'Bottom center',
					'Hore vľavo' => 'Top left',
					'Hore vpravo' => 'Top right',
					'Hore v strede' => 'Top center',
					'Stred obrazovky' => 'Center of screen',
					'💡 Box – kompaktný popup v rohu. Bar – horizontálny pruh cez celú šírku. Cloud – zaoblený popup s väčším tieňom.' => '💡 Box: compact popup in a corner. Bar: horizontal strip across full width. Cloud: rounded popup with a larger shadow.',
					'Poloha ikony' => 'Icon position',
					'Typ ikony' => 'Icon type',
					'Zobraziť plávajúcu ikonu' => 'Show floating icon',
					'Po udelení súhlasu sa zobrazí ikona na opätovnú správu preferencií.' => 'After consent is granted, the icon appears for managing preferences again.',
					'💡 Odporúčame zapnúť – GDPR vyžaduje, aby mohol používateľ kedykoľvek odvolať súhlas. Po kliknutí na ikonu sa zobrazí panel s ID súhlasu a tlačidlami.' => '💡 We recommend enabling this. GDPR requires users to be able to withdraw consent at any time. Clicking the icon opens a panel with consent ID and action buttons.',
					'CSS font-family hodnota' => 'CSS font-family value',
					'Zaoblenie tlačidiel (px)' => 'Button border radius (px)',
					'Zaoblenie bannera / modálu (px)' => 'Banner / modal border radius (px)',
					'💡 "inherit" = použije font témy. Príklad: "Inter, sans-serif". Font musí byť načítaný na stránke.' => '💡 "inherit" uses the theme font. Example: "Inter, sans-serif". The font must be loaded on the page.',
					'💡 0 = hranaté, 8 = mierne zaoblené, 24+ = "pill" tvar.' => '💡 0 = square corners, 8 = slightly rounded, 24+ = pill shape.',
					'💡 Zaoblenie rohov bannera aj modálu. Predvolené: 12 px.' => '💡 Corner radius for both banner and modal. Default: 12 px.',
					'Farby bannera' => 'Banner colors',
					'Nastavte farby pre pozadie a text cookie lišty (bannera).' => 'Set colors for cookie banner background and text.',
					'Pozadie bannera' => 'Banner background',
					'Farba pozadia cookie lišty.' => 'Cookie banner background color.',
					'Farba textu bannera' => 'Banner text color',
					'Farba nadpisu a popisu v banneri.' => 'Banner heading and description color.',
					'Tlačidlo "Prijať všetky" (primárne)' => '"Accept all" button (primary)',
					'Farebné nastavenia pre hlavné modré tlačidlo súhlasu. Prázdne pole = použije sa primárna farba.' => 'Color settings for the main consent button. Empty value = primary color is used.',
					'Pozadie (hover)' => 'Background (hover)',
					'Farba textu' => 'Text color',
					'Farba textu (hover)' => 'Text color (hover)',
					'Tlačidlo "Odmietnuť všetky" (primárne)' => '"Reject All" button (primary)',
					'Farebné nastavenia pre tlačidlo odmietnutia.' => 'Color settings for reject button.',
					'Farba ohraničenia' => 'Border color',
					'Tlačidlo "Spravovať nastavenia" (outline)' => '"Manage preferences" button (outline)',
					'Farebné nastavenia pre tlačidlo správy preferencií.' => 'Color settings for manage preferences button.',
					'Priehľadné' => 'Transparent',
					'Okno modálu (Spravovať súhlas)' => 'Modal window (Manage consent)',
					'Farby pre okno nastavenia cookies, ktoré sa otvorí po kliknutí na "Spravovať nastavenia".' => 'Colors for the cookie settings modal opened by "Manage preferences".',
					'Pozadie modálu' => 'Modal background',
					'Pozadie hlavičky' => 'Header background',
					'Pozadie päty' => 'Footer background',
					'Farba ohraničení' => 'Border color',
					'Pozadie kategórie' => 'Category background',
					'Pozadie kategórie (hover)' => 'Category background (hover)',
					'Farba prepínača (zapnutý)' => 'Toggle color (on)',
					'Farba textu "Vždy aktívne"' => '"Always active" text color',
					'Zaoblenie modálu (px)' => 'Modal border radius (px)',
					'Kliknite na jazyk – všetky polia sa vyplnia automaticky. Potom kliknite Uložiť.' => 'Click a language and all fields will be filled automatically. Then click Save.',
					'Popis cookie je viditeľný návštevníkom v modáli preferencií – pomáha im pochopiť, na čo daná cookie slúži.' => 'Cookie description is visible to visitors in the preferences modal and helps explain what the cookie is used for.',
					'viditeľný návštevníkom' => 'visible to visitors',
					'Žiadne cookies. Kliknite "+ Pridať cookie".' => 'No cookies. Click "+ Add cookie".',
					'Definujte zdroje skriptov, ktoré sa majú blokovať, kým používateľ neudelí súhlas pre danú kategóriu. Plugin zmení typ skriptu na text/plain, čo zabrání jeho spusteniu.' => 'Define script sources to block until the user grants consent for a given category. The plugin changes script type to text/plain to prevent execution.',
					'Žiadne pravidlá blokovania.' => 'No blocking rules.',
					'Nev.' => 'Nec.',
					'Anal.' => 'Analyt.',
					'Market.' => 'Mkt.',
					'Pref.' => 'Pref.',
					'ID súhlasu návštevníka' => 'Visitor consent ID',
					'Zobrazí jedinečné ID súhlasu aktuálneho návštevníka. Vhodné pre zásady ochrany osobných údajov – umožní používateľovi preukázať, kedy a ako súhlasil.' => 'Displays the unique consent ID of the current visitor. Useful for privacy policies and proving when/how the user consented.',
					'Text pred ID.' => 'Text before ID.',
					'HTML obal (p, div, span…)' => 'HTML wrapper (p, div, span...)',
					'Zoznam cookies používaných na webe' => 'List of cookies used on the website',
					'Automaticky zobrazí prehľadnú tabuľku všetkých deklarovaných cookies, rozdelenú podľa kategórií. Vložte na stránku s cookie politikou.' => 'Automatically displays a clear table of all declared cookies grouped by category. Insert on the cookie policy page.',
					'Tlačidlo správy súhlasu' => 'Consent management button',
					'Vloží tlačidlo, ktoré otvorí modál nastavenia cookies. Vhodné pre stránky so zásadami ochrany osobných údajov a právne dokumenty – umožní návštevníkovi kedykoľvek zmeniť preferencie.' => 'Inserts a button that opens the cookie settings modal. Suitable for privacy/legal pages and lets visitors change preferences anytime.',
					'Text tlačidla (predvolene: text z nastavení Prekladov).' => 'Button text (default: text from Translation settings).',
					'CSS trieda pre vlastné štýlovanie.' => 'CSS class for custom styling.',
					'Voliteľné HTML id atribút.' => 'Optional HTML id attribute.',
					'Exportuje všetky nastavenia do JSON súboru. Vhodné pre presun medzi servermi alebo zálohu.' => 'Exports all settings to a JSON file. Useful for migration between servers or backup.',
					'Nahrajte predtým exportovaný settings.json. Prepisuje aktuálnu konfiguráciu.' => 'Upload previously exported settings.json. It overwrites current configuration.',
					'Kliknite alebo presuňte settings.json sem' => 'Click or drag settings.json here',
					'Resetuje všetky nastavenia na predvolené hodnoty (SK jazyk, predvolený vzhľad). Deklarácie cookies, pravidlá blokovania a záznamy súhlasov nie sú ovplyvnené.' => 'Resets all settings to defaults (SK language, default appearance). Cookie declarations, blocking rules and consent logs are not affected.',
					'Plugin vytvoril Web Pixel Studio. Pre otázky, návrhy alebo hlásenie chýb nás kontaktujte na:' => 'Plugin created by Web Pixel Studio. For questions, suggestions or bug reports contact us at:',
					'Plugin je bezplatný a open-source pod licenciou GPL-2.0. Postavený na:' => 'The plugin is free and open-source under GPL-2.0. Built on:',
					'Prispôsobiteľný popup/bar/cloud banner s výberom polohy na stránke.' => 'Customizable popup/bar/cloud banner with selectable position on the page.',
					'Používateľ si môže zvoliť, ktoré kategórie cookies povolí (nevyhnutné, analytické, marketingové, preferenčné).' => 'Users can choose which cookie categories to allow (necessary, analytics, marketing, preferences).',
					'Každý súhlas sa uloží do databázy s ID, IP adresou, URL a časovou pečiatkou. Export do CSV.' => 'Each consent is stored in database with ID, IP, URL and timestamp. CSV export.',
					'Skripty tretích strán (napr. Google Analytics, Meta Pixel) sa zablokujú, kým používateľ neudelí súhlas.' => 'Third-party scripts (e.g. Google Analytics, Meta Pixel) are blocked until user grants consent.',
					'Farby, font, zaoblenie tlačidiel, rozloženie bannera, poloha floating ikony.' => 'Colors, font, button radius, banner layout, floating icon position.',
					'SK, EN, CS, DE, FR, ES, PL, HU, IT. Všetky texty sú plne editovateľné z admin panelu.' => 'SK, EN, CS, DE, FR, ES, PL, HU, IT. All texts are fully editable from the admin panel.',
					'Nastavenia je možné exportovať do JSON a importovať na inom webe.' => 'Settings can be exported to JSON and imported on another website.',
					'Banner sa automaticky skryje pred vyhľadávačmi a crawlermi.' => 'Banner is automatically hidden from search engines and crawlers.',
					'Plávajúca ikona umožní používateľovi kedykoľvek zmeniť preferencie. Po kliknutí zobrazí ID súhlasu a dátum.' => 'Floating icon lets users change preferences anytime. After click it shows consent ID and date.',
					'V záložke Nastavenia zapnite Zaznamenávať súhlasy, Opätovný súhlas, Skryť pre robotov a Automatické spustenie. Vyberte verziu Consent Mode (v2 pre väčšinu webov). Ak používate GTM, vyplňte GTM Container ID.' => 'In Settings tab enable Record consents, Re-consent, Hide from bots and Automatic launch. Select Consent Mode version (v2 for most websites). If you use GTM, fill GTM Container ID.',
					'V záložke Preklady vyberte jazyk pomocou rýchlych predvolieb alebo upravte texty manuálne. Kliknite Uložiť preklady.' => 'In Translations tab choose language using quick presets or edit texts manually. Click Save translations.',
					'V záložke Vzhľad nastavte farby, rozloženie bannera a polohu plávajúcej ikony. Použite tlačidlá Náhľad na overenie zmien.' => 'In Appearance tab set colors, banner layout and floating icon position. Use Preview buttons to verify changes.',
					'V záložke Cookies pridajte všetky cookies, ktoré váš web používa. Pre každú cookie vyplňte názov, doménu, platnosť, popis a kategóriu. Popis bude viditeľný návštevníkovi.' => 'In Cookies tab add all cookies your website uses. For each cookie fill name, domain, expiry, description and category. Description is visible to visitors.',
					'V záložke Blokovanie skriptov pridajte pravidlá pre skripty, ktoré chcete blokovať. Napr. pre Google Analytics pridajte "google-analytics.com" → kategória Analytické.' => 'In Script Blocking tab add rules for scripts you want to block. For Google Analytics add "google-analytics.com" with Analytics category.',
					'Na stránku s Cookie politikou vložte [ccwps_cookie_list] pre automatickú tabuľku cookies, [ccwps_consent_id] pre zobrazenie ID súhlasu a [ccwps_manage_consent] pre tlačidlo zmeny preferencií.' => 'On Cookie Policy page insert [ccwps_cookie_list] for automatic cookie table, [ccwps_consent_id] for consent ID display and [ccwps_manage_consent] for preference change button.',
					'Otvorte web v incognito okne a overte, že sa banner zobrazí, súhlas sa zaznamená v záložke Záznamy súhlasov a floating ikona funguje správne.' => 'Open website in incognito and verify banner is shown, consent is logged in Consent Log tab, and floating icon works correctly.',
					'V záložke Nastavenia vyplňte GTM Container ID (napr. GTM-XXXXXXX). Plugin automaticky vloží GTM kód do hlavičky stránky spolu s Consent Mode default stavom (všetky signály = denied). Po udelení súhlasu sa GTM aktualizuje pomocou gtag(\'consent\', \'update\', ...).' => 'In Settings tab fill GTM Container ID (e.g. GTM-XXXXXXX). Plugin inserts GTM code into page head with Consent Mode default state (all signals = denied). After consent, GTM is updated with gtag(\'consent\', \'update\', ...).',
					'Nechajte GTM Container ID prázdne. Plugin automaticky vloží Consent Mode default stav pred GTM kód, takže default denied signály sa nastavia skôr, ako GTM spustí akékoľvek tagy. Toto je správne správanie podľa Google dokumentácie.' => 'Leave GTM Container ID empty. Plugin inserts Consent Mode default state before GTM code, so denied signals are set before GTM runs any tags. This matches Google documentation.',
					'V GTM nastavte pre každý tag Consent Settings. Pre Google Analytics (GA4): analytics_storage = Required. Pre Google Ads: ad_storage, ad_user_data, ad_personalization = Required. Tagy sa spustia len po udelení príslušného súhlasu.' => 'In GTM set Consent Settings for each tag. For GA4: analytics_storage = Required. For Google Ads: ad_storage, ad_user_data, ad_personalization = Required. Tags run only after required consent is granted.',
					'Otvorte Google Tag Assistant a overte, že pri odmietnutí cookies sú tagy v stave "Consent Blocked" a po udelení súhlasu sa aktivujú. Skontrolujte tiež Google Analytics Realtime report.' => 'Open Google Tag Assistant and verify tags are in "Consent Blocked" when cookies are rejected, and activate after consent. Also check Google Analytics Realtime report.',
					'Advanced Cookie Consent for EU je bezplatný WordPress plugin pre správu súhlasov s cookies (GDPR / ePrivacy). Poskytuje plne prispôsobiteľný banner a modál preferencií, zaznamenáva súhlasy pre GDPR audit, blokuje skripty tretích strán a podporuje Google Consent Mode v2 a v3.' => 'Advanced Cookie Consent for EU is a free WordPress plugin for cookie consent management (GDPR / ePrivacy). It provides a fully customizable banner and preferences modal, records consents for GDPR audits, blocks third-party scripts, and supports Google Consent Mode v2 and v3.',
					'Plugin je postavený na knižnici orest bida (cookieconsent) a rozširuje ju o WordPress admin panel, databázové záznamy súhlasov a blokovanie skriptov.' => 'The plugin is built on the orest bida cookieconsent library and extends it with a WordPress admin panel, consent database logs, and script blocking.',
					'Automaticky nastaví default denied stav a aktualizuje Google signály po udelení súhlasu.' => 'Automatically sets default denied state and updates Google signals after consent is granted.',
					'Plné prispôsobenie vzhľadu' => 'Full appearance customization',
					'9 jazykových predvolieb' => '9 language presets',
					'[ccwps_consent_id] – zobrazí ID súhlasu návštevníka. [ccwps_cookie_list] – tabuľka deklarovaných cookies. [ccwps_manage_consent] – tlačidlo na správu súhlasu.' => '[ccwps_consent_id] displays visitor consent ID. [ccwps_cookie_list] shows the declared cookies table. [ccwps_manage_consent] is a consent management button.',
					'[ccwps_consent_id] – zobrazí Visitor consent ID. [ccwps_cookie_list] – tabuľka deklarovaných cookies. [ccwps_manage_consent] – tlačidlo na správu súhlasu.' => '[ccwps_consent_id] displays visitor consent ID. [ccwps_cookie_list] shows the declared cookies table. [ccwps_manage_consent] is a consent management button.',
					'Detekcia robotov' => 'Bot detection',
					'Opätovný súhlas' => 'Re-consent',
					'Ak sa zmení zoznam cookies, plugin automaticky požiada o nový súhlas.' => 'If the cookie list changes, the plugin automatically asks for new consent.',
					'Floating ikona' => 'Floating icon',
					'Cookie politika' => 'Cookie policy',
					'Overenie' => 'Verification',
					'Možnosť A: Plugin načíta GTM automaticky' => 'Option A: Plugin loads GTM automatically',
					'Možnosť B: GTM máte nainštalovaný inak (téma, iný plugin)' => 'Option B: GTM is installed differently (theme, another plugin)',
					'Nastavenie tagov v GTM' => 'GTM tag setup',
					'Overenie pomocou Google Tag Assistant' => 'Verification with Google Tag Assistant',
					'Verzia' => 'Version',
					'Deklarácie cookies' => 'Cookie declarations',
					'Pravidlá blokovania' => 'Blocking rules',
					'Parameter' => 'Parameter',
					'Predvolené' => 'Default',
					'ID vášho súhlasu' => 'Your consent ID',
					'(všetky)' => '(all)',
					'Filtruj: necessary, analytics, targeting, preferences' => 'Filter: necessary, analytics, targeting, preferences',
					'Viditeľný návštevníkom v modáli preferencií.' => 'Visible to visitors in the preferences modal.',
					'Primárna / akcentová farba' => 'Primary / accent color',
					'Používa sa ako fallback farba pre tlačidlá a zvýraznenia.' => 'Used as fallback color for buttons and highlights.',
					'Tlačidlo "Prijať všetky" (primárne)' => '"Accept all" button (primary)',
					'Tlačidlo "Odmietnuť všetky" (primárne)' => '"Reject All" button (primary)',
					'Tlačidlo "Spravovať nastavenia" (outline)' => '"Manage preferences" button (outline)',
					'Pozadie' => 'Background',
					'Farby pre okno nastavenia cookies, ktoré sa otvorí po kliknutí na "Spravovať nastavenia".' => 'Colors for the cookie settings modal opened by clicking "Manage preferences".',
					'Text color "Vždy aktívne"' => 'Text color "Always active"',
					'Farby pre okno nastavenia cookies, ktoré sa otvorí po kliknutí na "Manage preferences".' => 'Colors for the cookie settings modal opened by clicking "Manage preferences".',
					'Farby pre okno nastavenia cookies, ktoré sa otvorí po kliknutí na &quot;Spravovať nastavenia&quot;.' => 'Colors for the cookie settings modal opened by clicking "Manage preferences".',
					'Je Regex?' => 'Is Regex?',
					'Žiadne cookies. Kliknite "+ Add cookie".' => 'No cookies. Click "+ Add cookie".',
					'Žiadne cookies. Kliknite &quot;+ Add cookie&quot;.' => 'No cookies. Click "+ Add cookie".',
					'V záložke Script Blocking pridajte pravidlá pre skripty, ktoré chcete blokovať. Napr. pre Google Analytics pridajte "google-analytics.com" → kategória Analytické.' => 'In Script Blocking tab add rules for scripts you want to block. For Google Analytics add "google-analytics.com" with Analytics category.',
					'V záložke Script Blocking pridajte pravidlá pre skripty, ktoré chcete blokovať. Napr. pre Google Analytics pridajte &quot;google-analytics.com&quot; → kategória Analytické.' => 'In Script Blocking tab add rules for scripts you want to block. For Google Analytics add "google-analytics.com" with Analytics category.',
					'V záložke Settings vyplňte GTM Container ID (napr. GTM-XXXXXXX). Plugin automaticky vloží GTM kód do hlavičky stránky spolu s Consent Mode default stavom (všetky signály = denied). Po udelení súhlasu sa GTM aktualizuje pomocou gtag(\'consent\', \'update\', ...).' => 'In Settings tab fill GTM Container ID (e.g. GTM-XXXXXXX). Plugin inserts GTM code into page head with Consent Mode default state (all signals = denied). After consent, GTM is updated with gtag(\'consent\', \'update\', ...).',
					'V záložke Settings vyplňte GTM Container ID (napr. GTM-XXXXXXX). Plugin automaticky vloží GTM kód do hlavičky stránky spolu s Consent Mode default stavom (všetky signály = denied). Po udelení súhlasu sa GTM aktualizuje pomocou gtag(&#039;consent&#039;, &#039;update&#039;, ...).' => 'In Settings tab fill GTM Container ID (e.g. GTM-XXXXXXX). Plugin inserts GTM code into page head with Consent Mode default state (all signals = denied). After consent, GTM is updated with gtag(\'consent\', \'update\', ...).',
					'Otvorte Google Tag Assistant a overte, že pri odmietnutí cookies sú tagy v stave &quot;Consent Blocked&quot; a po udelení súhlasu sa aktivujú. Skontrolujte tiež Google Analytics Realtime report.' => 'Open Google Tag Assistant and verify tags are in "Consent Blocked" when cookies are rejected and activate after consent. Also check Google Analytics Realtime report.',
					'Vždy aktívne' => 'Always active',
					'Vlastná ikona' => 'Custom icon',
					'Žiadny obrázok' => 'No image',
					'Vybrať vlastnú ikonu' => 'Select custom icon',
					'Použiť tento obrázok' => 'Use this image',
					'Zadajte názov cookie.' => 'Enter cookie name.',
					'Zadajte zdroj skriptu.' => 'Enter script source.',
					'Ukladám…' => 'Saving...',
					'Uložiť nastavenia' => 'Save settings',
					'Pridať cookie' => 'Add cookie',
					'Upraviť cookie' => 'Edit cookie',
					'Pridať pravidlo' => 'Add rule',
					'Upraviť pravidlo' => 'Edit rule',
					'Žiadne cookies nie sú deklarované.' => 'No cookies are declared.',
				],
				'strings' => [
					'lang_banner_title'       => 'We use cookies',
					'lang_banner_description' => 'We use cookies to enhance your browsing experience, serve personalised content, and analyse our traffic. By clicking "Accept All", you consent to our use of cookies.',
					'lang_accept_all'         => 'Accept All',
					'lang_reject_all'         => 'Reject All',
					'lang_manage_preferences' => 'Customize',
					'lang_save_preferences'   => 'Save Preferences',
					'lang_close'              => 'Close',
					'lang_consent_id_label'   => 'Your consent ID',
					'lang_always_on'          => 'Always active',
					'lang_cookie_name'        => 'Name',
					'lang_cookie_domain'      => 'Domain',
					'lang_cookie_expiration'  => 'Expiration',
					'lang_cookie_description' => 'Description',
					'lang_necessary_title'    => 'Necessary',
					'lang_necessary_desc'     => 'Necessary cookies help make a website usable by enabling basic functions like page navigation and access to secure areas. The website cannot function properly without these cookies.',
					'lang_analytics_title'    => 'Analytics',
					'lang_analytics_desc'     => 'Analytics cookies help website owners understand how visitors interact with websites by collecting and reporting information anonymously.',
					'lang_targeting_title'    => 'Targeting',
					'lang_targeting_desc'     => 'Targeting cookies are used to deliver advertisements more relevant to you and your interests. They are also used to limit the number of times you see an advertisement.',
					'lang_preferences_title'  => 'Preferences',
					'lang_preferences_desc'   => 'Preference cookies enable a website to remember information that changes the way the website behaves or looks, like your preferred language or the region you are in.',
					'lang_powered_by'         => 'Web Pixel Studio',
				],
			],

			'sk' => [
				'label'     => 'Slovenčina',
				'flag'      => '🇸🇰',
				'flag_file' => 'SK',
				'admin_strings' => [
					'admin_lang_label'              => 'Jazyk:',
					'admin_nav_settings'            => 'Nastavenia',
					'admin_nav_appearance'          => 'Vzhľad',
					'admin_nav_translations'        => 'Preklady',
					'admin_nav_cookies'             => 'Cookies',
					'admin_nav_blocking'            => 'Blokovanie skriptov',
					'admin_nav_log'                 => 'Záznamy súhlasov',
					'admin_nav_shortcodes'          => 'Shortcodes',
					'admin_nav_tools'               => 'Nástroje',
					'admin_nav_about'               => 'O plugine',
					'admin_preview_banner'          => 'Zobraziť banner',
					'admin_preview_modal'           => 'Nastavenia cookies',
					'admin_preview_label'           => 'Náhľad:',
					'admin_tab_settings_h1'         => 'Nastavenia správania',
					'admin_tab_appearance_h1'       => 'Vzhľad bannera',
					'admin_tab_translations_h1'     => 'Preklady frontendu',
					'admin_tab_cookies_h1'          => 'Deklarácia cookies',
					'admin_tab_blocking_h1'         => 'Blokovanie skriptov',
					'admin_tab_log_h1'              => 'Záznamy súhlasov',
					'admin_tab_tools_h1'            => 'Nástroje',
					'admin_sect_banner_behavior'    => 'Správanie bannera',
					'admin_sect_cookie_settings'    => 'Nastavenia cookie súhlasu',
					'admin_sect_layout'             => 'Rozloženie a poloha bannera',
					'admin_sect_floating_icon'      => 'Plávajúca ikona',
					'admin_sect_typography'         => 'Typografia a zaoblenie',
					'admin_sect_lang_presets'       => 'Rýchle jazykové predvoľby',
					'admin_sect_export'             => 'Export nastavení',
					'admin_sect_import'             => 'Import nastavení',
					'admin_sect_reset'              => 'Reset na predvolené',
					'admin_sect_plugin_info'        => 'Informácie o plugine',
					'admin_btn_save_settings'       => 'Uložiť nastavenia',
					'admin_btn_save_appearance'     => 'Uložiť vzhľad',
					'admin_btn_save_translations'   => 'Uložiť preklady',
					'admin_btn_add_cookie'          => 'Pridať cookie',
					'admin_btn_add_rule'            => 'Pridať pravidlo',
					'admin_btn_edit'                => 'Upraviť',
					'admin_btn_delete'              => 'Zmazať',
					'admin_btn_cancel'              => 'Zrušiť',
					'admin_btn_save'                => 'Uložiť',
					'admin_btn_copy'                => 'Kopírovať',
					'admin_btn_export_csv'          => 'Exportovať CSV',
					'admin_btn_clear_log'           => 'Vymazať všetky záznamy',
					'admin_btn_export_json'         => 'Stiahnuť settings.json',
					'admin_btn_import_json'         => 'Importovať nastavenia',
					'admin_btn_reset'               => 'Resetovať nastavenia',
					'admin_btn_remove'              => 'Odstrániť',
					'admin_btn_show_list'           => 'Zobraziť zoznam',
					'admin_tip_label'               => 'Tip / Nápoveda',
					'admin_col_name'                => 'Názov',
					'admin_col_domain'              => 'Doména',
					'admin_col_expiry'              => 'Platnosť',
					'admin_col_description'         => 'Popis',
					'admin_col_category'            => 'Kategória',
					'admin_col_actions'             => 'Akcie',
					'admin_col_script_source'       => 'Zdroj skriptu',
					'admin_col_date'                => 'Dátum',
					'admin_col_consent_id'          => 'ID súhlasu',
					'admin_col_ip'                  => 'IP adresa',
					'admin_col_updated'             => 'Aktualizácia',
					'admin_trans_sect_modal'        => 'Modál preferencií',
					'admin_trans_sect_cookie_table' => 'Tabuľka cookies',
					'admin_trans_sect_categories'   => 'Kategórie cookies',
					'admin_trans_banner_title'      => 'Nadpis bannera',
					'admin_trans_banner_desc'       => 'Popis bannera',
					'admin_trans_accept_all'        => 'Tlačidlo "Prijať všetky"',
					'admin_trans_reject_all'        => 'Tlačidlo "Odmietnuť všetky"',
					'admin_trans_manage_pref'       => 'Tlačidlo "Prispôsobiť"',
					'admin_trans_powered_by'        => 'Text "Powered by" (odkaz na wps.sk)',
					'admin_trans_save_pref'         => 'Tlačidlo "Uložiť nastavenia"',
					'admin_trans_close'             => 'Tlačidlo "Zavrieť"',
					'admin_trans_consent_id'        => 'Popis ID súhlasu',
					'admin_trans_always_on'         => 'Štítok "Vždy aktívne"',
					'admin_trans_col_name'          => 'Stĺpec Názov',
					'admin_trans_col_domain'        => 'Stĺpec Doména',
					'admin_trans_col_expiry'        => 'Stĺpec Platnosť',
					'admin_trans_col_desc'          => 'Stĺpec Popis',
					'admin_trans_necessary_title'   => 'Nevyhnutné – Nadpis',
					'admin_trans_necessary_desc'    => 'Nevyhnutné – Popis',
					'admin_trans_analytics_title'   => 'Analytické – Nadpis',
					'admin_trans_analytics_desc'    => 'Analytické – Popis',
					'admin_trans_targeting_title'   => 'Marketingové – Nadpis',
					'admin_trans_targeting_desc'    => 'Marketingové – Popis',
					'admin_trans_preferences_title' => 'Preferenčné – Nadpis',
					'admin_trans_preferences_desc'  => 'Preferenčné – Popis',
				],
				'strings' => [
					'lang_banner_title'       => 'Používame súbory cookie',
					'lang_banner_description' => 'Používame súbory cookie na zlepšenie vášho zážitku z prehliadania, poskytovanie personalizovaného obsahu a analýzu návštevnosti. Kliknutím na „Prijať všetky" súhlasíte s používaním súborov cookie.',
					'lang_accept_all'         => 'Prijať všetky',
					'lang_reject_all'         => 'Odmietnuť všetky',
					'lang_manage_preferences' => 'Prispôsobiť',
					'lang_save_preferences'   => 'Uložiť nastavenia',
					'lang_close'              => 'Zavrieť',
					'lang_consent_id_label'   => 'ID vášho súhlasu',
					'lang_always_on'          => 'Vždy aktívne',
					'lang_cookie_name'        => 'Názov',
					'lang_cookie_domain'      => 'Doména',
					'lang_cookie_expiration'  => 'Platnosť',
					'lang_cookie_description' => 'Popis',
					'lang_necessary_title'    => 'Nevyhnutné',
					'lang_necessary_desc'     => 'Nevyhnutné súbory cookie pomáhajú, aby bola webová stránka použiteľná, a to tak, že umožňujú základné funkcie, ako je navigácia po stránkach a prístup k zabezpečeným oblastiam. Webová stránka nemôže bez týchto súborov cookie správne fungovať.',
					'lang_analytics_title'    => 'Analytické',
					'lang_analytics_desc'     => 'Analytické súbory cookie pomáhajú vlastníkom webových stránok pochopiť, ako návštevníci interagujú s webovými stránkami, a to prostredníctvom anonymného zberu a vykazovania informácií.',
					'lang_targeting_title'    => 'Marketingové',
					'lang_targeting_desc'     => 'Marketingové súbory cookie sa používajú na zobrazovanie reklám relevantných pre vás a vaše záujmy. Používajú sa tiež na obmedzenie počtu zobrazení reklamy.',
					'lang_preferences_title'  => 'Preferenčné',
					'lang_preferences_desc'   => 'Preferenčné súbory cookie umožňujú webovej stránke zapamätať si informácie, ktoré menia spôsob, akým sa webová stránka správa alebo vyzerá, napríklad váš preferovaný jazyk alebo región.',
					'lang_powered_by'         => 'Web Pixel Studio',
				],
			],

			'cs' => [
				'label'     => 'Čeština',
				'flag'      => '🇨🇿',
				'flag_file' => 'CZ',
				'admin_strings' => [
					'admin_lang_label'              => 'Jazyk:',
					'admin_nav_settings'            => 'Nastavení',
					'admin_nav_appearance'          => 'Vzhled',
					'admin_nav_translations'        => 'Překlady',
					'admin_nav_cookies'             => 'Cookies',
					'admin_nav_blocking'            => 'Blokování skriptů',
					'admin_nav_log'                 => 'Záznamy souhlasů',
					'admin_nav_shortcodes'          => 'Shortcodes',
					'admin_nav_tools'               => 'Nástroje',
					'admin_nav_about'               => 'O pluginu',
					'admin_preview_banner'          => 'Zobrazit banner',
					'admin_preview_modal'           => 'Nastavení cookies',
					'admin_preview_label'           => 'Náhled:',
					'admin_tab_settings_h1'         => 'Nastavení chování',
					'admin_tab_appearance_h1'       => 'Vzhled banneru',
					'admin_tab_translations_h1'     => 'Překlady frontendu',
					'admin_tab_cookies_h1'          => 'Deklarace cookies',
					'admin_tab_blocking_h1'         => 'Blokování skriptů',
					'admin_tab_log_h1'              => 'Záznamy souhlasů',
					'admin_tab_tools_h1'            => 'Nástroje',
					'admin_sect_banner_behavior'    => 'Chování banneru',
					'admin_sect_cookie_settings'    => 'Nastavení cookie souhlasu',
					'admin_sect_layout'             => 'Rozložení a poloha banneru',
					'admin_sect_floating_icon'      => 'Plovoucí ikona',
					'admin_sect_typography'         => 'Typografie a zaoblení',
					'admin_sect_lang_presets'       => 'Rychlé jazykové předvolby',
					'admin_sect_export'             => 'Export nastavení',
					'admin_sect_import'             => 'Import nastavení',
					'admin_sect_reset'              => 'Reset na výchozí hodnoty',
					'admin_sect_plugin_info'        => 'Informace o pluginu',
					'admin_btn_save_settings'       => 'Uložit nastavení',
					'admin_btn_save_appearance'     => 'Uložit vzhled',
					'admin_btn_save_translations'   => 'Uložit překlady',
					'admin_btn_add_cookie'          => 'Přidat cookie',
					'admin_btn_add_rule'            => 'Přidat pravidlo',
					'admin_btn_edit'                => 'Upravit',
					'admin_btn_delete'              => 'Smazat',
					'admin_btn_cancel'              => 'Zrušit',
					'admin_btn_save'                => 'Uložit',
					'admin_btn_copy'                => 'Kopírovat',
					'admin_btn_export_csv'          => 'Exportovat CSV',
					'admin_btn_clear_log'           => 'Vymazat všechny záznamy',
					'admin_btn_export_json'         => 'Stáhnout settings.json',
					'admin_btn_import_json'         => 'Importovat nastavení',
					'admin_btn_reset'               => 'Resetovat nastavení',
					'admin_btn_remove'              => 'Odebrat',
					'admin_btn_show_list'           => 'Zobrazit seznam',
					'admin_tip_label'               => 'Tip / Nápověda',
					'admin_col_name'                => 'Název',
					'admin_col_domain'              => 'Doména',
					'admin_col_expiry'              => 'Platnost',
					'admin_col_description'         => 'Popis',
					'admin_col_category'            => 'Kategorie',
					'admin_col_actions'             => 'Akce',
					'admin_col_script_source'       => 'Zdroj skriptu',
					'admin_col_date'                => 'Datum',
					'admin_col_consent_id'          => 'ID souhlasu',
					'admin_col_ip'                  => 'IP adresa',
					'admin_col_updated'             => 'Aktualizace',
					'admin_trans_sect_modal'        => 'Modál preferencí',
					'admin_trans_sect_cookie_table' => 'Tabulka cookies',
					'admin_trans_sect_categories'   => 'Kategorie cookies',
					'admin_trans_banner_title'      => 'Nadpis banneru',
					'admin_trans_banner_desc'       => 'Popis banneru',
					'admin_trans_accept_all'        => 'Tlačítko "Přijmout vše"',
					'admin_trans_reject_all'        => 'Tlačítko "Odmítnout vše"',
					'admin_trans_manage_pref'       => 'Tlačítko "Přizpůsobit"',
					'admin_trans_powered_by'        => 'Text "Powered by" (odkaz na wps.sk)',
					'admin_trans_save_pref'         => 'Tlačítko "Uložit nastavení"',
					'admin_trans_close'             => 'Tlačítko "Zavřít"',
					'admin_trans_consent_id'        => 'Popis ID souhlasu',
					'admin_trans_always_on'         => 'Štítek "Vždy aktivní"',
					'admin_trans_col_name'          => 'Sloupec Název',
					'admin_trans_col_domain'        => 'Sloupec Doména',
					'admin_trans_col_expiry'        => 'Sloupec Platnost',
					'admin_trans_col_desc'          => 'Sloupec Popis',
					'admin_trans_necessary_title'   => 'Nezbytné – Nadpis',
					'admin_trans_necessary_desc'    => 'Nezbytné – Popis',
					'admin_trans_analytics_title'   => 'Analytické – Nadpis',
					'admin_trans_analytics_desc'    => 'Analytické – Popis',
					'admin_trans_targeting_title'   => 'Marketingové – Nadpis',
					'admin_trans_targeting_desc'    => 'Marketingové – Popis',
					'admin_trans_preferences_title' => 'Preferenční – Nadpis',
					'admin_trans_preferences_desc'  => 'Preferenční – Popis',
				],
				'strings' => [
					'lang_banner_title'       => 'Používáme soubory cookie',
					'lang_banner_description' => 'Používáme soubory cookie ke zlepšení vašeho zážitku z prohlížení, poskytování personalizovaného obsahu a analýze provozu. Kliknutím na „Přijmout vše" souhlasíte s používáním souborů cookie.',
					'lang_accept_all'         => 'Přijmout vše',
					'lang_reject_all'         => 'Odmítnout vše',
					'lang_manage_preferences' => 'Přizpůsobit',
					'lang_save_preferences'   => 'Uložit nastavení',
					'lang_close'              => 'Zavřít',
					'lang_consent_id_label'   => 'ID vašeho souhlasu',
					'lang_always_on'          => 'Vždy aktivní',
					'lang_cookie_name'        => 'Název',
					'lang_cookie_domain'      => 'Doména',
					'lang_cookie_expiration'  => 'Platnost',
					'lang_cookie_description' => 'Popis',
					'lang_necessary_title'    => 'Nezbytné',
					'lang_necessary_desc'     => 'Nezbytné soubory cookie pomáhají, aby byl web použitelný, a to tak, že umožňují základní funkce, jako je navigace na stránce a přístup k zabezpečeným oblastem webu. Web nemůže bez těchto souborů cookie správně fungovat.',
					'lang_analytics_title'    => 'Analytické',
					'lang_analytics_desc'     => 'Analytické soubory cookie pomáhají majitelům webových stránek pochopit, jak návštěvníci interagují s webovými stránkami, a to shromažďováním a hlášením informací anonymně.',
					'lang_targeting_title'    => 'Marketingové',
					'lang_targeting_desc'     => 'Marketingové soubory cookie se používají k zobrazování reklam relevantních pro vás a vaše zájmy. Používají se také k omezení počtu zobrazení reklamy.',
					'lang_preferences_title'  => 'Preferenční',
					'lang_preferences_desc'   => 'Preferenční soubory cookie umožňují webové stránce zapamatovat si informace, které mění způsob, jakým se webová stránka chová nebo vypadá.',
					'lang_powered_by'         => 'Web Pixel Studio',
				],
			],

			'de' => [
				'label'     => 'Deutsch',
				'flag'      => '🇩🇪',
				'flag_file' => 'DE',
				'admin_strings' => [
					'admin_lang_label'              => 'Sprache:',
					'admin_nav_settings'            => 'Einstellungen',
					'admin_nav_appearance'          => 'Erscheinungsbild',
					'admin_nav_translations'        => 'Übersetzungen',
					'admin_nav_cookies'             => 'Cookies',
					'admin_nav_blocking'            => 'Skriptblockierung',
					'admin_nav_log'                 => 'Einwilligungsprotokoll',
					'admin_nav_shortcodes'          => 'Shortcodes',
					'admin_nav_tools'               => 'Werkzeuge',
					'admin_nav_about'               => 'Über das Plugin',
					'admin_preview_banner'          => 'Banner anzeigen',
					'admin_preview_modal'           => 'Cookie-Einstellungen',
					'admin_preview_label'           => 'Vorschau:',
					'admin_tab_settings_h1'         => 'Verhaltenseinstellungen',
					'admin_tab_appearance_h1'       => 'Banner-Darstellung',
					'admin_tab_translations_h1'     => 'Frontend-Übersetzungen',
					'admin_tab_cookies_h1'          => 'Cookie-Deklaration',
					'admin_tab_blocking_h1'         => 'Skriptblockierung',
					'admin_tab_log_h1'              => 'Einwilligungsprotokoll',
					'admin_tab_tools_h1'            => 'Werkzeuge',
					'admin_sect_banner_behavior'    => 'Banner-Verhalten',
					'admin_sect_cookie_settings'    => 'Cookie-Einwilligungseinstellungen',
					'admin_sect_layout'             => 'Banner-Layout und Position',
					'admin_sect_floating_icon'      => 'Schwebendes Symbol',
					'admin_sect_typography'         => 'Typografie und Eckenradius',
					'admin_sect_lang_presets'       => 'Schnelle Sprach-Voreinstellungen',
					'admin_sect_export'             => 'Einstellungen exportieren',
					'admin_sect_import'             => 'Einstellungen importieren',
					'admin_sect_reset'              => 'Auf Standardwerte zurücksetzen',
					'admin_sect_plugin_info'        => 'Plugin-Informationen',
					'admin_btn_save_settings'       => 'Einstellungen speichern',
					'admin_btn_save_appearance'     => 'Darstellung speichern',
					'admin_btn_save_translations'   => 'Übersetzungen speichern',
					'admin_btn_add_cookie'          => 'Cookie hinzufügen',
					'admin_btn_add_rule'            => 'Regel hinzufügen',
					'admin_btn_edit'                => 'Bearbeiten',
					'admin_btn_delete'              => 'Löschen',
					'admin_btn_cancel'              => 'Abbrechen',
					'admin_btn_save'                => 'Speichern',
					'admin_btn_copy'                => 'Kopieren',
					'admin_btn_export_csv'          => 'CSV exportieren',
					'admin_btn_clear_log'           => 'Alle Einträge löschen',
					'admin_btn_export_json'         => 'settings.json herunterladen',
					'admin_btn_import_json'         => 'Einstellungen importieren',
					'admin_btn_reset'               => 'Einstellungen zurücksetzen',
					'admin_btn_remove'              => 'Entfernen',
					'admin_btn_show_list'           => 'Liste anzeigen',
					'admin_tip_label'               => 'Tipp / Hilfe',
					'admin_col_name'                => 'Name',
					'admin_col_domain'              => 'Domain',
					'admin_col_expiry'              => 'Ablauf',
					'admin_col_description'         => 'Beschreibung',
					'admin_col_category'            => 'Kategorie',
					'admin_col_actions'             => 'Aktionen',
					'admin_col_script_source'       => 'Skriptquelle',
					'admin_col_date'                => 'Datum',
					'admin_col_consent_id'          => 'Einwilligungs-ID',
					'admin_col_ip'                  => 'IP-Adresse',
					'admin_col_updated'             => 'Aktualisiert',
					'admin_trans_sect_modal'        => 'Präferenz-Modal',
					'admin_trans_sect_cookie_table' => 'Cookie-Tabelle',
					'admin_trans_sect_categories'   => 'Cookie-Kategorien',
					'admin_trans_banner_title'      => 'Banner-Titel',
					'admin_trans_banner_desc'       => 'Banner-Beschreibung',
					'admin_trans_accept_all'        => 'Schaltfläche "Alle akzeptieren"',
					'admin_trans_reject_all'        => 'Schaltfläche "Alle ablehnen"',
					'admin_trans_manage_pref'       => 'Schaltfläche "Anpassen"',
					'admin_trans_powered_by'        => '"Powered by"-Link-Text',
					'admin_trans_save_pref'         => 'Schaltfläche "Einstellungen speichern"',
					'admin_trans_close'             => 'Schaltfläche "Schließen"',
					'admin_trans_consent_id'        => 'Einwilligungs-ID-Beschreibung',
					'admin_trans_always_on'         => 'Etikett "Immer aktiv"',
					'admin_trans_col_name'          => 'Spalte: Name',
					'admin_trans_col_domain'        => 'Spalte: Domain',
					'admin_trans_col_expiry'        => 'Spalte: Ablauf',
					'admin_trans_col_desc'          => 'Spalte: Beschreibung',
					'admin_trans_necessary_title'   => 'Notwendig – Titel',
					'admin_trans_necessary_desc'    => 'Notwendig – Beschreibung',
					'admin_trans_analytics_title'   => 'Statistik – Titel',
					'admin_trans_analytics_desc'    => 'Statistik – Beschreibung',
					'admin_trans_targeting_title'   => 'Marketing – Titel',
					'admin_trans_targeting_desc'    => 'Marketing – Beschreibung',
					'admin_trans_preferences_title' => 'Präferenzen – Titel',
					'admin_trans_preferences_desc'  => 'Präferenzen – Beschreibung',
				],
				'strings' => [
					'lang_banner_title'       => 'Wir verwenden Cookies',
					'lang_banner_description' => 'Wir verwenden Cookies, um Ihr Surferlebnis zu verbessern, personalisierte Inhalte bereitzustellen und unseren Datenverkehr zu analysieren. Durch Klicken auf „Alle akzeptieren" stimmen Sie der Verwendung von Cookies zu.',
					'lang_accept_all'         => 'Alle akzeptieren',
					'lang_reject_all'         => 'Alle ablehnen',
					'lang_manage_preferences' => 'Anpassen',
					'lang_save_preferences'   => 'Einstellungen speichern',
					'lang_close'              => 'Schließen',
					'lang_consent_id_label'   => 'Ihre Einwilligungs-ID',
					'lang_always_on'          => 'Immer aktiv',
					'lang_cookie_name'        => 'Name',
					'lang_cookie_domain'      => 'Domain',
					'lang_cookie_expiration'  => 'Ablauf',
					'lang_cookie_description' => 'Beschreibung',
					'lang_necessary_title'    => 'Notwendig',
					'lang_necessary_desc'     => 'Notwendige Cookies helfen dabei, eine Webseite nutzbar zu machen, indem sie Grundfunktionen wie Seitennavigation und Zugriff auf sichere Bereiche ermöglichen. Ohne diese Cookies kann die Website nicht ordnungsgemäß funktionieren.',
					'lang_analytics_title'    => 'Statistik',
					'lang_analytics_desc'     => 'Statistik-Cookies helfen Webseiten-Besitzern zu verstehen, wie Besucher mit Webseiten interagieren, indem Informationen anonym gesammelt und gemeldet werden.',
					'lang_targeting_title'    => 'Marketing',
					'lang_targeting_desc'     => 'Marketing-Cookies werden verwendet, um Werbeanzeigen zu schalten, die für Sie und Ihre Interessen relevanter sind. Sie werden auch verwendet, um die Anzahl der Anzeigen zu begrenzen.',
					'lang_preferences_title'  => 'Präferenzen',
					'lang_preferences_desc'   => 'Präferenz-Cookies ermöglichen einer Webseite, Informationen zu speichern, die die Art und Weise beeinflussen, wie sich eine Webseite verhält oder aussieht.',
					'lang_powered_by'         => 'Web Pixel Studio',
				],
			],

			'fr' => [
				'label'     => 'Français',
				'flag'      => '🇫🇷',
				'flag_file' => 'FR',
				'admin_strings' => [
					'admin_lang_label'              => 'Langue :',
					'admin_nav_settings'            => 'Paramètres',
					'admin_nav_appearance'          => 'Apparence',
					'admin_nav_translations'        => 'Traductions',
					'admin_nav_cookies'             => 'Cookies',
					'admin_nav_blocking'            => 'Blocage de scripts',
					'admin_nav_log'                 => 'Journal des consentements',
					'admin_nav_shortcodes'          => 'Shortcodes',
					'admin_nav_tools'               => 'Outils',
					'admin_nav_about'               => 'À propos',
					'admin_preview_banner'          => 'Afficher la bannière',
					'admin_preview_modal'           => 'Paramètres cookies',
					'admin_preview_label'           => 'Aperçu :',
					'admin_tab_settings_h1'         => 'Paramètres de comportement',
					'admin_tab_appearance_h1'       => 'Apparence de la bannière',
					'admin_tab_translations_h1'     => 'Traductions frontend',
					'admin_tab_cookies_h1'          => 'Déclaration des cookies',
					'admin_tab_blocking_h1'         => 'Blocage de scripts',
					'admin_tab_log_h1'              => 'Journal des consentements',
					'admin_tab_tools_h1'            => 'Outils',
					'admin_sect_banner_behavior'    => 'Comportement de la bannière',
					'admin_sect_cookie_settings'    => 'Paramètres du consentement aux cookies',
					'admin_sect_layout'             => 'Disposition et position de la bannière',
					'admin_sect_floating_icon'      => 'Icône flottante',
					'admin_sect_typography'         => 'Typographie et rayon de bordure',
					'admin_sect_lang_presets'       => 'Préréglages de langue rapides',
					'admin_sect_export'             => 'Exporter les paramètres',
					'admin_sect_import'             => 'Importer les paramètres',
					'admin_sect_reset'              => 'Réinitialiser les paramètres',
					'admin_sect_plugin_info'        => 'Informations sur le plugin',
					'admin_btn_save_settings'       => 'Enregistrer les paramètres',
					'admin_btn_save_appearance'     => "Enregistrer l'apparence",
					'admin_btn_save_translations'   => 'Enregistrer les traductions',
					'admin_btn_add_cookie'          => 'Ajouter un cookie',
					'admin_btn_add_rule'            => 'Ajouter une règle',
					'admin_btn_edit'                => 'Modifier',
					'admin_btn_delete'              => 'Supprimer',
					'admin_btn_cancel'              => 'Annuler',
					'admin_btn_save'                => 'Enregistrer',
					'admin_btn_copy'                => 'Copier',
					'admin_btn_export_csv'          => 'Exporter en CSV',
					'admin_btn_clear_log'           => 'Effacer tous les enregistrements',
					'admin_btn_export_json'         => 'Télécharger settings.json',
					'admin_btn_import_json'         => 'Importer les paramètres',
					'admin_btn_reset'               => 'Réinitialiser les paramètres',
					'admin_btn_remove'              => 'Supprimer',
					'admin_btn_show_list'           => 'Afficher la liste',
					'admin_tip_label'               => 'Conseil / Aide',
					'admin_col_name'                => 'Nom',
					'admin_col_domain'              => 'Domaine',
					'admin_col_expiry'              => 'Expiration',
					'admin_col_description'         => 'Description',
					'admin_col_category'            => 'Catégorie',
					'admin_col_actions'             => 'Actions',
					'admin_col_script_source'       => 'Source du script',
					'admin_col_date'                => 'Date',
					'admin_col_consent_id'          => 'ID de consentement',
					'admin_col_ip'                  => 'Adresse IP',
					'admin_col_updated'             => 'Mis à jour',
					'admin_trans_sect_modal'        => 'Fenêtre des préférences',
					'admin_trans_sect_cookie_table' => 'Tableau des cookies',
					'admin_trans_sect_categories'   => 'Catégories de cookies',
					'admin_trans_banner_title'      => 'Titre de la bannière',
					'admin_trans_banner_desc'       => 'Description de la bannière',
					'admin_trans_accept_all'        => 'Bouton "Tout accepter"',
					'admin_trans_reject_all'        => 'Bouton "Tout refuser"',
					'admin_trans_manage_pref'       => 'Bouton "Personnaliser"',
					'admin_trans_powered_by'        => 'Texte du lien "Powered by"',
					'admin_trans_save_pref'         => 'Bouton "Enregistrer les préférences"',
					'admin_trans_close'             => 'Bouton "Fermer"',
					'admin_trans_consent_id'        => "Étiquette de l'ID de consentement",
					'admin_trans_always_on'         => 'Étiquette "Toujours actif"',
					'admin_trans_col_name'          => 'Colonne : Nom',
					'admin_trans_col_domain'        => 'Colonne : Domaine',
					'admin_trans_col_expiry'        => 'Colonne : Expiration',
					'admin_trans_col_desc'          => 'Colonne : Description',
					'admin_trans_necessary_title'   => 'Nécessaires – Titre',
					'admin_trans_necessary_desc'    => 'Nécessaires – Description',
					'admin_trans_analytics_title'   => 'Statistiques – Titre',
					'admin_trans_analytics_desc'    => 'Statistiques – Description',
					'admin_trans_targeting_title'   => 'Marketing – Titre',
					'admin_trans_targeting_desc'    => 'Marketing – Description',
					'admin_trans_preferences_title' => 'Préférences – Titre',
					'admin_trans_preferences_desc'  => 'Préférences – Description',
				],
				'strings' => [
					'lang_banner_title'       => 'Nous utilisons des cookies',
					'lang_banner_description' => "Nous utilisons des cookies pour améliorer votre expérience de navigation, diffuser du contenu personnalisé et analyser notre trafic. En cliquant sur « Tout accepter », vous consentez à notre utilisation des cookies.",
					'lang_accept_all'         => 'Tout accepter',
					'lang_reject_all'         => 'Tout refuser',
					'lang_manage_preferences' => 'Personnaliser',
					'lang_save_preferences'   => 'Enregistrer les préférences',
					'lang_close'              => 'Fermer',
					'lang_consent_id_label'   => 'Votre ID de consentement',
					'lang_always_on'          => 'Toujours actif',
					'lang_cookie_name'        => 'Nom',
					'lang_cookie_domain'      => 'Domaine',
					'lang_cookie_expiration'  => 'Expiration',
					'lang_cookie_description' => 'Description',
					'lang_necessary_title'    => 'Nécessaires',
					'lang_necessary_desc'     => "Les cookies nécessaires contribuent à rendre un site Web utilisable en activant des fonctions de base comme la navigation de page et l'accès aux zones sécurisées du site Web.",
					'lang_analytics_title'    => 'Statistiques',
					'lang_analytics_desc'     => "Les cookies de statistiques aident les propriétaires du site Web, par la collecte et la communication d'informations de manière anonyme, à comprendre comment les visiteurs interagissent avec les sites Web.",
					'lang_targeting_title'    => 'Marketing',
					'lang_targeting_desc'     => "Les cookies marketing sont utilisés pour effectuer le suivi des visiteurs au travers des sites Web. Le but est d'afficher des publicités qui sont pertinentes et intéressantes pour l'utilisateur individuel.",
					'lang_preferences_title'  => 'Préférences',
					'lang_preferences_desc'   => 'Les cookies de préférences permettent au site Web de mémoriser des informations qui modifient son comportement ou son apparence.',
					'lang_powered_by'         => 'Web Pixel Studio',
				],
			],

			'es' => [
				'label'     => 'Español',
				'flag'      => '🇪🇸',
				'flag_file' => 'ES',
				'admin_strings' => [
					'admin_lang_label'              => 'Idioma:',
					'admin_nav_settings'            => 'Configuración',
					'admin_nav_appearance'          => 'Apariencia',
					'admin_nav_translations'        => 'Traducciones',
					'admin_nav_cookies'             => 'Cookies',
					'admin_nav_blocking'            => 'Bloqueo de scripts',
					'admin_nav_log'                 => 'Registro de consentimientos',
					'admin_nav_shortcodes'          => 'Shortcodes',
					'admin_nav_tools'               => 'Herramientas',
					'admin_nav_about'               => 'Acerca del plugin',
					'admin_preview_banner'          => 'Mostrar banner',
					'admin_preview_modal'           => 'Configuración de cookies',
					'admin_preview_label'           => 'Vista previa:',
					'admin_tab_settings_h1'         => 'Configuración de comportamiento',
					'admin_tab_appearance_h1'       => 'Apariencia del banner',
					'admin_tab_translations_h1'     => 'Traducciones frontend',
					'admin_tab_cookies_h1'          => 'Declaración de cookies',
					'admin_tab_blocking_h1'         => 'Bloqueo de scripts',
					'admin_tab_log_h1'              => 'Registro de consentimientos',
					'admin_tab_tools_h1'            => 'Herramientas',
					'admin_sect_banner_behavior'    => 'Comportamiento del banner',
					'admin_sect_cookie_settings'    => 'Configuración del consentimiento de cookies',
					'admin_sect_layout'             => 'Diseño y posición del banner',
					'admin_sect_floating_icon'      => 'Icono flotante',
					'admin_sect_typography'         => 'Tipografía y radio de borde',
					'admin_sect_lang_presets'       => 'Preajustes de idioma rápidos',
					'admin_sect_export'             => 'Exportar configuración',
					'admin_sect_import'             => 'Importar configuración',
					'admin_sect_reset'              => 'Restablecer configuración',
					'admin_sect_plugin_info'        => 'Información del plugin',
					'admin_btn_save_settings'       => 'Guardar configuración',
					'admin_btn_save_appearance'     => 'Guardar apariencia',
					'admin_btn_save_translations'   => 'Guardar traducciones',
					'admin_btn_add_cookie'          => 'Agregar cookie',
					'admin_btn_add_rule'            => 'Agregar regla',
					'admin_btn_edit'                => 'Editar',
					'admin_btn_delete'              => 'Eliminar',
					'admin_btn_cancel'              => 'Cancelar',
					'admin_btn_save'                => 'Guardar',
					'admin_btn_copy'                => 'Copiar',
					'admin_btn_export_csv'          => 'Exportar CSV',
					'admin_btn_clear_log'           => 'Borrar todos los registros',
					'admin_btn_export_json'         => 'Descargar settings.json',
					'admin_btn_import_json'         => 'Importar configuración',
					'admin_btn_reset'               => 'Restablecer configuración',
					'admin_btn_remove'              => 'Eliminar',
					'admin_btn_show_list'           => 'Mostrar lista',
					'admin_tip_label'               => 'Consejo / Ayuda',
					'admin_col_name'                => 'Nombre',
					'admin_col_domain'              => 'Dominio',
					'admin_col_expiry'              => 'Caducidad',
					'admin_col_description'         => 'Descripción',
					'admin_col_category'            => 'Categoría',
					'admin_col_actions'             => 'Acciones',
					'admin_col_script_source'       => 'Fuente del script',
					'admin_col_date'                => 'Fecha',
					'admin_col_consent_id'          => 'ID de consentimiento',
					'admin_col_ip'                  => 'Dirección IP',
					'admin_col_updated'             => 'Actualizado',
					'admin_trans_sect_modal'        => 'Ventana de preferencias',
					'admin_trans_sect_cookie_table' => 'Tabla de cookies',
					'admin_trans_sect_categories'   => 'Categorías de cookies',
					'admin_trans_banner_title'      => 'Título del banner',
					'admin_trans_banner_desc'       => 'Descripción del banner',
					'admin_trans_accept_all'        => 'Botón "Aceptar todo"',
					'admin_trans_reject_all'        => 'Botón "Rechazar todo"',
					'admin_trans_manage_pref'       => 'Botón "Personalizar"',
					'admin_trans_powered_by'        => 'Texto del enlace "Powered by"',
					'admin_trans_save_pref'         => 'Botón "Guardar preferencias"',
					'admin_trans_close'             => 'Botón "Cerrar"',
					'admin_trans_consent_id'        => 'Etiqueta de ID de consentimiento',
					'admin_trans_always_on'         => 'Etiqueta "Siempre activo"',
					'admin_trans_col_name'          => 'Columna: Nombre',
					'admin_trans_col_domain'        => 'Columna: Dominio',
					'admin_trans_col_expiry'        => 'Columna: Caducidad',
					'admin_trans_col_desc'          => 'Columna: Descripción',
					'admin_trans_necessary_title'   => 'Necesarias – Título',
					'admin_trans_necessary_desc'    => 'Necesarias – Descripción',
					'admin_trans_analytics_title'   => 'Estadísticas – Título',
					'admin_trans_analytics_desc'    => 'Estadísticas – Descripción',
					'admin_trans_targeting_title'   => 'Marketing – Título',
					'admin_trans_targeting_desc'    => 'Marketing – Descripción',
					'admin_trans_preferences_title' => 'Preferencias – Título',
					'admin_trans_preferences_desc'  => 'Preferencias – Descripción',
				],
				'strings' => [
					'lang_banner_title'       => 'Usamos cookies',
					'lang_banner_description' => 'Usamos cookies para mejorar su experiencia de navegación, mostrar contenido personalizado y analizar nuestro tráfico. Al hacer clic en "Aceptar todo", acepta el uso de cookies.',
					'lang_accept_all'         => 'Aceptar todo',
					'lang_reject_all'         => 'Rechazar todo',
					'lang_manage_preferences' => 'Personalizar',
					'lang_save_preferences'   => 'Guardar preferencias',
					'lang_close'              => 'Cerrar',
					'lang_consent_id_label'   => 'Su ID de consentimiento',
					'lang_always_on'          => 'Siempre activo',
					'lang_cookie_name'        => 'Nombre',
					'lang_cookie_domain'      => 'Dominio',
					'lang_cookie_expiration'  => 'Caducidad',
					'lang_cookie_description' => 'Descripción',
					'lang_necessary_title'    => 'Necesarias',
					'lang_necessary_desc'     => 'Las cookies necesarias ayudan a hacer una página web utilizable activando funciones básicas como la navegación en la página y el acceso a áreas seguras de la página web.',
					'lang_analytics_title'    => 'Estadísticas',
					'lang_analytics_desc'     => 'Las cookies de estadísticas ayudan a los propietarios de páginas web a comprender cómo interactúan los visitantes con las páginas web reuniendo y proporcionando información de forma anónima.',
					'lang_targeting_title'    => 'Marketing',
					'lang_targeting_desc'     => 'Las cookies de marketing se utilizan para rastrear a los visitantes en las páginas web. La intención es mostrar anuncios relevantes y atractivos para el usuario individual.',
					'lang_preferences_title'  => 'Preferencias',
					'lang_preferences_desc'   => 'Las cookies de preferencias permiten a la página web recordar información que cambia la forma en que la página se comporta o el aspecto que tiene.',
					'lang_powered_by'         => 'Web Pixel Studio',
				],
			],

			'pl' => [
				'label'     => 'Polski',
				'flag'      => '🇵🇱',
				'flag_file' => 'PL',
				'admin_strings' => [
					'admin_lang_label'              => 'Język:',
					'admin_nav_settings'            => 'Ustawienia',
					'admin_nav_appearance'          => 'Wygląd',
					'admin_nav_translations'        => 'Tłumaczenia',
					'admin_nav_cookies'             => 'Cookies',
					'admin_nav_blocking'            => 'Blokowanie skryptów',
					'admin_nav_log'                 => 'Dziennik zgód',
					'admin_nav_shortcodes'          => 'Shortcodes',
					'admin_nav_tools'               => 'Narzędzia',
					'admin_nav_about'               => 'O wtyczce',
					'admin_preview_banner'          => 'Pokaż baner',
					'admin_preview_modal'           => 'Ustawienia cookies',
					'admin_preview_label'           => 'Podgląd:',
					'admin_tab_settings_h1'         => 'Ustawienia zachowania',
					'admin_tab_appearance_h1'       => 'Wygląd baneru',
					'admin_tab_translations_h1'     => 'Tłumaczenia frontendu',
					'admin_tab_cookies_h1'          => 'Deklaracja cookies',
					'admin_tab_blocking_h1'         => 'Blokowanie skryptów',
					'admin_tab_log_h1'              => 'Dziennik zgód',
					'admin_tab_tools_h1'            => 'Narzędzia',
					'admin_sect_banner_behavior'    => 'Zachowanie baneru',
					'admin_sect_cookie_settings'    => 'Ustawienia zgody na cookies',
					'admin_sect_layout'             => 'Układ i pozycja baneru',
					'admin_sect_floating_icon'      => 'Pływająca ikona',
					'admin_sect_typography'         => 'Typografia i promień krawędzi',
					'admin_sect_lang_presets'       => 'Szybkie ustawienia językowe',
					'admin_sect_export'             => 'Eksport ustawień',
					'admin_sect_import'             => 'Import ustawień',
					'admin_sect_reset'              => 'Resetuj do domyślnych',
					'admin_sect_plugin_info'        => 'Informacje o wtyczce',
					'admin_btn_save_settings'       => 'Zapisz ustawienia',
					'admin_btn_save_appearance'     => 'Zapisz wygląd',
					'admin_btn_save_translations'   => 'Zapisz tłumaczenia',
					'admin_btn_add_cookie'          => 'Dodaj cookie',
					'admin_btn_add_rule'            => 'Dodaj regułę',
					'admin_btn_edit'                => 'Edytuj',
					'admin_btn_delete'              => 'Usuń',
					'admin_btn_cancel'              => 'Anuluj',
					'admin_btn_save'                => 'Zapisz',
					'admin_btn_copy'                => 'Kopiuj',
					'admin_btn_export_csv'          => 'Eksportuj CSV',
					'admin_btn_clear_log'           => 'Wyczyść wszystkie rekordy',
					'admin_btn_export_json'         => 'Pobierz settings.json',
					'admin_btn_import_json'         => 'Importuj ustawienia',
					'admin_btn_reset'               => 'Zresetuj ustawienia',
					'admin_btn_remove'              => 'Usuń',
					'admin_btn_show_list'           => 'Pokaż listę',
					'admin_tip_label'               => 'Wskazówka / Pomoc',
					'admin_col_name'                => 'Nazwa',
					'admin_col_domain'              => 'Domena',
					'admin_col_expiry'              => 'Ważność',
					'admin_col_description'         => 'Opis',
					'admin_col_category'            => 'Kategoria',
					'admin_col_actions'             => 'Akcje',
					'admin_col_script_source'       => 'Źródło skryptu',
					'admin_col_date'                => 'Data',
					'admin_col_consent_id'          => 'ID zgody',
					'admin_col_ip'                  => 'Adres IP',
					'admin_col_updated'             => 'Zaktualizowano',
					'admin_trans_sect_modal'        => 'Modal preferencji',
					'admin_trans_sect_cookie_table' => 'Tabela cookies',
					'admin_trans_sect_categories'   => 'Kategorie cookies',
					'admin_trans_banner_title'      => 'Tytuł baneru',
					'admin_trans_banner_desc'       => 'Opis baneru',
					'admin_trans_accept_all'        => 'Przycisk "Zaakceptuj wszystkie"',
					'admin_trans_reject_all'        => 'Przycisk "Odrzuć wszystkie"',
					'admin_trans_manage_pref'       => 'Przycisk "Dostosuj"',
					'admin_trans_powered_by'        => 'Tekst linku "Powered by"',
					'admin_trans_save_pref'         => 'Przycisk "Zapisz preferencje"',
					'admin_trans_close'             => 'Przycisk "Zamknij"',
					'admin_trans_consent_id'        => 'Etykieta ID zgody',
					'admin_trans_always_on'         => 'Etykieta "Zawsze aktywne"',
					'admin_trans_col_name'          => 'Kolumna: Nazwa',
					'admin_trans_col_domain'        => 'Kolumna: Domena',
					'admin_trans_col_expiry'        => 'Kolumna: Ważność',
					'admin_trans_col_desc'          => 'Kolumna: Opis',
					'admin_trans_necessary_title'   => 'Niezbędne – Tytuł',
					'admin_trans_necessary_desc'    => 'Niezbędne – Opis',
					'admin_trans_analytics_title'   => 'Statystyczne – Tytuł',
					'admin_trans_analytics_desc'    => 'Statystyczne – Opis',
					'admin_trans_targeting_title'   => 'Marketingowe – Tytuł',
					'admin_trans_targeting_desc'    => 'Marketingowe – Opis',
					'admin_trans_preferences_title' => 'Preferencje – Tytuł',
					'admin_trans_preferences_desc'  => 'Preferencje – Opis',
				],
				'strings' => [
					'lang_banner_title'       => 'Używamy plików cookie',
					'lang_banner_description' => 'Używamy plików cookie, aby ulepszyć Twoje przeglądanie, wyświetlać spersonalizowane treści i analizować nasz ruch. Klikając „Zaakceptuj wszystkie", wyrażasz zgodę na używanie przez nas plików cookie.',
					'lang_accept_all'         => 'Zaakceptuj wszystkie',
					'lang_reject_all'         => 'Odrzuć wszystkie',
					'lang_manage_preferences' => 'Dostosuj',
					'lang_save_preferences'   => 'Zapisz preferencje',
					'lang_close'              => 'Zamknij',
					'lang_consent_id_label'   => 'ID Twojej zgody',
					'lang_always_on'          => 'Zawsze aktywne',
					'lang_cookie_name'        => 'Nazwa',
					'lang_cookie_domain'      => 'Domena',
					'lang_cookie_expiration'  => 'Okres ważności',
					'lang_cookie_description' => 'Opis',
					'lang_necessary_title'    => 'Niezbędne',
					'lang_necessary_desc'     => 'Niezbędne pliki cookie przyczyniają się do użyteczności strony przez umożliwienie podstawowych funkcji takich jak nawigacja na stronie i dostęp do bezpiecznych obszarów strony internetowej.',
					'lang_analytics_title'    => 'Statystyczne',
					'lang_analytics_desc'     => 'Statystyczne pliki cookie pomagają właścicielom stron internetowych zrozumieć, jak odwiedzający wchodzą w interakcje ze stronami internetowymi poprzez anonimowe zbieranie i raportowanie informacji.',
					'lang_targeting_title'    => 'Marketingowe',
					'lang_targeting_desc'     => 'Marketingowe pliki cookie stosowane są w celu śledzenia odwiedzających na stronach internetowych. Celem jest wyświetlanie reklam, które są istotne i interesujące dla poszczególnych użytkowników.',
					'lang_preferences_title'  => 'Preferencje',
					'lang_preferences_desc'   => 'Preferencyjne pliki cookie pozwalają stronie zapamiętać informacje, które zmieniają zachowanie lub wygląd strony.',
					'lang_powered_by'         => 'Web Pixel Studio',
				],
			],

			'hu' => [
				'label'     => 'Magyar',
				'flag'      => '🇭🇺',
				'flag_file' => 'HU',
				'admin_strings' => [
					'admin_lang_label'              => 'Nyelv:',
					'admin_nav_settings'            => 'Beállítások',
					'admin_nav_appearance'          => 'Megjelenés',
					'admin_nav_translations'        => 'Fordítások',
					'admin_nav_cookies'             => 'Cookies',
					'admin_nav_blocking'            => 'Szkriptblokkolás',
					'admin_nav_log'                 => 'Hozzájárulási napló',
					'admin_nav_shortcodes'          => 'Shortcodes',
					'admin_nav_tools'               => 'Eszközök',
					'admin_nav_about'               => 'A bővítményről',
					'admin_preview_banner'          => 'Banner megjelenítése',
					'admin_preview_modal'           => 'Cookie-beállítások',
					'admin_preview_label'           => 'Előnézet:',
					'admin_tab_settings_h1'         => 'Viselkedési beállítások',
					'admin_tab_appearance_h1'       => 'Banner megjelenése',
					'admin_tab_translations_h1'     => 'Frontend fordítások',
					'admin_tab_cookies_h1'          => 'Sütik deklarációja',
					'admin_tab_blocking_h1'         => 'Szkriptblokkolás',
					'admin_tab_log_h1'              => 'Hozzájárulási napló',
					'admin_tab_tools_h1'            => 'Eszközök',
					'admin_sect_banner_behavior'    => 'Banner viselkedése',
					'admin_sect_cookie_settings'    => 'Cookie-hozzájárulás beállításai',
					'admin_sect_layout'             => 'Banner elrendezése és pozíciója',
					'admin_sect_floating_icon'      => 'Lebegő ikon',
					'admin_sect_typography'         => 'Tipográfia és lekerekítés',
					'admin_sect_lang_presets'       => 'Gyors nyelvi előbeállítások',
					'admin_sect_export'             => 'Beállítások exportálása',
					'admin_sect_import'             => 'Beállítások importálása',
					'admin_sect_reset'              => 'Visszaállítás alapértelmezettre',
					'admin_sect_plugin_info'        => 'Plugin-információk',
					'admin_btn_save_settings'       => 'Beállítások mentése',
					'admin_btn_save_appearance'     => 'Megjelenés mentése',
					'admin_btn_save_translations'   => 'Fordítások mentése',
					'admin_btn_add_cookie'          => 'Cookie hozzáadása',
					'admin_btn_add_rule'            => 'Szabály hozzáadása',
					'admin_btn_edit'                => 'Szerkesztés',
					'admin_btn_delete'              => 'Törlés',
					'admin_btn_cancel'              => 'Mégse',
					'admin_btn_save'                => 'Mentés',
					'admin_btn_copy'                => 'Másolás',
					'admin_btn_export_csv'          => 'CSV exportálás',
					'admin_btn_clear_log'           => 'Összes rekord törlése',
					'admin_btn_export_json'         => 'settings.json letöltése',
					'admin_btn_import_json'         => 'Beállítások importálása',
					'admin_btn_reset'               => 'Beállítások visszaállítása',
					'admin_btn_remove'              => 'Eltávolítás',
					'admin_btn_show_list'           => 'Lista megjelenítése',
					'admin_tip_label'               => 'Tipp / Súgó',
					'admin_col_name'                => 'Név',
					'admin_col_domain'              => 'Tartomány',
					'admin_col_expiry'              => 'Lejárat',
					'admin_col_description'         => 'Leírás',
					'admin_col_category'            => 'Kategória',
					'admin_col_actions'             => 'Műveletek',
					'admin_col_script_source'       => 'Szkript forrása',
					'admin_col_date'                => 'Dátum',
					'admin_col_consent_id'          => 'Hozzájárulás ID',
					'admin_col_ip'                  => 'IP-cím',
					'admin_col_updated'             => 'Frissítve',
					'admin_trans_sect_modal'        => 'Preferencia-ablak',
					'admin_trans_sect_cookie_table' => 'Süti-táblázat',
					'admin_trans_sect_categories'   => 'Süti-kategóriák',
					'admin_trans_banner_title'      => 'Banner-cím',
					'admin_trans_banner_desc'       => 'Banner-leírás',
					'admin_trans_accept_all'        => '"Összes elfogadása" gomb',
					'admin_trans_reject_all'        => '"Összes elutasítása" gomb',
					'admin_trans_manage_pref'       => '"Testreszabás" gomb',
					'admin_trans_powered_by'        => '"Powered by" link szövege',
					'admin_trans_save_pref'         => '"Beállítások mentése" gomb',
					'admin_trans_close'             => '"Bezárás" gomb',
					'admin_trans_consent_id'        => 'Hozzájárulás-azonosító felirat',
					'admin_trans_always_on'         => '"Mindig bekapcsolt" felirat',
					'admin_trans_col_name'          => 'Oszlop: Név',
					'admin_trans_col_domain'        => 'Oszlop: Tartomány',
					'admin_trans_col_expiry'        => 'Oszlop: Lejárat',
					'admin_trans_col_desc'          => 'Oszlop: Leírás',
					'admin_trans_necessary_title'   => 'Szükséges – Cím',
					'admin_trans_necessary_desc'    => 'Szükséges – Leírás',
					'admin_trans_analytics_title'   => 'Statisztikai – Cím',
					'admin_trans_analytics_desc'    => 'Statisztikai – Leírás',
					'admin_trans_targeting_title'   => 'Marketing – Cím',
					'admin_trans_targeting_desc'    => 'Marketing – Leírás',
					'admin_trans_preferences_title' => 'Preferenciák – Cím',
					'admin_trans_preferences_desc'  => 'Preferenciák – Leírás',
				],
				'strings' => [
					'lang_banner_title'       => 'Sütiket használunk',
					'lang_banner_description' => 'Sütiket használunk a böngészési élmény javítása, személyre szabott tartalom megjelenítése és a forgalmunk elemzése érdekében. Az „Összes elfogadása" gombra kattintva hozzájárul a sütik használatához.',
					'lang_accept_all'         => 'Összes elfogadása',
					'lang_reject_all'         => 'Összes elutasítása',
					'lang_manage_preferences' => 'Testreszabás',
					'lang_save_preferences'   => 'Beállítások mentése',
					'lang_close'              => 'Bezárás',
					'lang_consent_id_label'   => 'Az Ön hozzájárulási azonosítója',
					'lang_always_on'          => 'Mindig aktív',
					'lang_cookie_name'        => 'Név',
					'lang_cookie_domain'      => 'Domain',
					'lang_cookie_expiration'  => 'Lejárat',
					'lang_cookie_description' => 'Leírás',
					'lang_necessary_title'    => 'Szükséges',
					'lang_necessary_desc'     => 'A szükséges sütik segítenek használhatóvá tenni a weboldalt az alapfunkciók, például az oldalnavigáció és a biztonságos területekhez való hozzáférés engedélyezésével.',
					'lang_analytics_title'    => 'Statisztikai',
					'lang_analytics_desc'     => 'A statisztikai sütik segítenek a weboldal tulajdonosainak megérteni, hogy a látogatók hogyan lépnek kapcsolatba a weboldalakkal azáltal, hogy névtelen adatokat gyűjtenek és jelentenek.',
					'lang_targeting_title'    => 'Marketing',
					'lang_targeting_desc'     => 'A marketing sütiket a látogatók weboldalakon való nyomon követésére használják. A cél az, hogy az egyes felhasználók számára releváns és vonzó hirdetéseket jelenítsenek meg.',
					'lang_preferences_title'  => 'Preferenciák',
					'lang_preferences_desc'   => 'A preferencia sütik lehetővé teszik a weboldal számára, hogy emlékezzen az olyan információkra, amelyek megváltoztatják a weboldal viselkedését vagy megjelenését.',
					'lang_powered_by'         => 'Web Pixel Studio',
				],
			],

			'it' => [
				'label'     => 'Italiano',
				'flag'      => '🇮🇹',
				'flag_file' => 'IT',
				'admin_strings' => [
					'admin_lang_label'              => 'Lingua:',
					'admin_nav_settings'            => 'Impostazioni',
					'admin_nav_appearance'          => 'Aspetto',
					'admin_nav_translations'        => 'Traduzioni',
					'admin_nav_cookies'             => 'Cookies',
					'admin_nav_blocking'            => 'Blocco script',
					'admin_nav_log'                 => 'Registro consensi',
					'admin_nav_shortcodes'          => 'Shortcodes',
					'admin_nav_tools'               => 'Strumenti',
					'admin_nav_about'               => 'Informazioni',
					'admin_preview_banner'          => 'Mostra banner',
					'admin_preview_modal'           => 'Impostazioni cookie',
					'admin_preview_label'           => 'Anteprima:',
					'admin_tab_settings_h1'         => 'Impostazioni di comportamento',
					'admin_tab_appearance_h1'       => 'Aspetto del banner',
					'admin_tab_translations_h1'     => 'Traduzioni frontend',
					'admin_tab_cookies_h1'          => 'Dichiarazione cookie',
					'admin_tab_blocking_h1'         => 'Blocco script',
					'admin_tab_log_h1'              => 'Registro dei consensi',
					'admin_tab_tools_h1'            => 'Strumenti',
					'admin_sect_banner_behavior'    => 'Comportamento del banner',
					'admin_sect_cookie_settings'    => 'Impostazioni del consenso ai cookie',
					'admin_sect_layout'             => 'Layout e posizione del banner',
					'admin_sect_floating_icon'      => 'Icona fluttuante',
					'admin_sect_typography'         => 'Tipografia e raggio bordo',
					'admin_sect_lang_presets'       => 'Impostazioni lingua rapide',
					'admin_sect_export'             => 'Esporta impostazioni',
					'admin_sect_import'             => 'Importa impostazioni',
					'admin_sect_reset'              => 'Ripristina impostazioni predefinite',
					'admin_sect_plugin_info'        => 'Informazioni sul plugin',
					'admin_btn_save_settings'       => 'Salva impostazioni',
					'admin_btn_save_appearance'     => 'Salva aspetto',
					'admin_btn_save_translations'   => 'Salva traduzioni',
					'admin_btn_add_cookie'          => 'Aggiungi cookie',
					'admin_btn_add_rule'            => 'Aggiungi regola',
					'admin_btn_edit'                => 'Modifica',
					'admin_btn_delete'              => 'Elimina',
					'admin_btn_cancel'              => 'Annulla',
					'admin_btn_save'                => 'Salva',
					'admin_btn_copy'                => 'Copia',
					'admin_btn_export_csv'          => 'Esporta CSV',
					'admin_btn_clear_log'           => 'Cancella tutti i record',
					'admin_btn_export_json'         => 'Scarica settings.json',
					'admin_btn_import_json'         => 'Importa impostazioni',
					'admin_btn_reset'               => 'Ripristina impostazioni',
					'admin_btn_remove'              => 'Rimuovi',
					'admin_btn_show_list'           => 'Mostra elenco',
					'admin_tip_label'               => 'Suggerimento / Aiuto',
					'admin_col_name'                => 'Nome',
					'admin_col_domain'              => 'Dominio',
					'admin_col_expiry'              => 'Scadenza',
					'admin_col_description'         => 'Descrizione',
					'admin_col_category'            => 'Categoria',
					'admin_col_actions'             => 'Azioni',
					'admin_col_script_source'       => 'Sorgente script',
					'admin_col_date'                => 'Data',
					'admin_col_consent_id'          => 'ID consenso',
					'admin_col_ip'                  => 'Indirizzo IP',
					'admin_col_updated'             => 'Aggiornato',
					'admin_trans_sect_modal'        => 'Finestra preferenze',
					'admin_trans_sect_cookie_table' => 'Tabella cookie',
					'admin_trans_sect_categories'   => 'Categorie cookie',
					'admin_trans_banner_title'      => 'Titolo banner',
					'admin_trans_banner_desc'       => 'Descrizione banner',
					'admin_trans_accept_all'        => 'Pulsante "Accetta tutti"',
					'admin_trans_reject_all'        => 'Pulsante "Rifiuta tutti"',
					'admin_trans_manage_pref'       => 'Pulsante "Personalizza"',
					'admin_trans_powered_by'        => 'Testo link "Powered by"',
					'admin_trans_save_pref'         => 'Pulsante "Salva preferenze"',
					'admin_trans_close'             => 'Pulsante "Chiudi"',
					'admin_trans_consent_id'        => 'Etichetta ID consenso',
					'admin_trans_always_on'         => 'Etichetta "Sempre attivo"',
					'admin_trans_col_name'          => 'Colonna: Nome',
					'admin_trans_col_domain'        => 'Colonna: Dominio',
					'admin_trans_col_expiry'        => 'Colonna: Scadenza',
					'admin_trans_col_desc'          => 'Colonna: Descrizione',
					'admin_trans_necessary_title'   => 'Necessari – Titolo',
					'admin_trans_necessary_desc'    => 'Necessari – Descrizione',
					'admin_trans_analytics_title'   => 'Statistiche – Titolo',
					'admin_trans_analytics_desc'    => 'Statistiche – Descrizione',
					'admin_trans_targeting_title'   => 'Marketing – Titolo',
					'admin_trans_targeting_desc'    => 'Marketing – Descrizione',
					'admin_trans_preferences_title' => 'Preferenze – Titolo',
					'admin_trans_preferences_desc'  => 'Preferenze – Descrizione',
				],
				'strings' => [
					'lang_banner_title'       => 'Utilizziamo i cookie',
					'lang_banner_description' => "Utilizziamo i cookie per migliorare la tua esperienza di navigazione, fornire contenuti personalizzati e analizzare il nostro traffico. Facendo clic su \"Accetta tutti\", acconsenti all'uso dei cookie.",
					'lang_accept_all'         => 'Accetta tutti',
					'lang_reject_all'         => 'Rifiuta tutti',
					'lang_manage_preferences' => 'Personalizza',
					'lang_save_preferences'   => 'Salva preferenze',
					'lang_close'              => 'Chiudi',
					'lang_consent_id_label'   => 'Il tuo ID di consenso',
					'lang_always_on'          => 'Sempre attivo',
					'lang_cookie_name'        => 'Nome',
					'lang_cookie_domain'      => 'Dominio',
					'lang_cookie_expiration'  => 'Scadenza',
					'lang_cookie_description' => 'Descrizione',
					'lang_necessary_title'    => 'Necessari',
					'lang_necessary_desc'     => "I cookie necessari contribuiscono a rendere fruibile il sito web, abilitando funzionalità di base quali la navigazione sulle pagine e l'accesso alle aree protette del sito.",
					'lang_analytics_title'    => 'Statistiche',
					'lang_analytics_desc'     => 'I cookie di statistica aiutano i proprietari di siti web a capire come i visitatori interagiscono con i siti raccogliendo e trasmettendo informazioni in forma anonima.',
					'lang_targeting_title'    => 'Marketing',
					'lang_targeting_desc'     => "I cookie di marketing vengono utilizzati per tracciare i visitatori sui siti web. L'obiettivo è quello di visualizzare annunci pertinenti e coinvolgenti per il singolo utente.",
					'lang_preferences_title'  => 'Preferenze',
					'lang_preferences_desc'   => "I cookie relativi alle preferenze consentono al sito di memorizzare informazioni che ne influenzano il comportamento o l'aspetto.",
					'lang_powered_by'         => 'Web Pixel Studio',
				],
			],
		];
	}

	/**
	 * Get strings for a specific language code.
	 */
	public static function get( string $lang_code ): ?array {
		$all = self::get_all();
		return $all[ $lang_code ] ?? null;
	}

	/**
	 * Get list of languages for select dropdown (code => label).
	 */
	public static function get_labels(): array {
		$out = [];
		foreach ( self::get_all() as $code => $data ) {
			$out[ $code ] = $data['flag'] . ' ' . $data['label'];
		}
		return $out;
	}

	/**
	 * Returns admin text replacement map (phrase-level) for given language.
	 */
	public static function get_admin_text_map( string $lang_code ): array {
		$all        = self::get_all();
		$data       = $all[ $lang_code ] ?? null;
		$built_in   = [];
		$file_map   = self::load_admin_texts( $lang_code );

		if ( is_array( $data ) && ! empty( $data['admin_texts'] ) && is_array( $data['admin_texts'] ) ) {
			$built_in = $data['admin_texts'];
		}

		if ( ! empty( $built_in ) || ! empty( $file_map ) ) {
			return array_replace( $built_in, $file_map );
		}

		// Fallback: if language has no dedicated admin text map yet, use English map.
		$en           = $all['en'] ?? null;
		$en_built_in  = [];
		$en_file_map  = self::load_admin_texts( 'en' );

		if ( is_array( $en ) && ! empty( $en['admin_texts'] ) && is_array( $en['admin_texts'] ) ) {
			$en_built_in = $en['admin_texts'];
		}

		if ( ! empty( $en_built_in ) || ! empty( $en_file_map ) ) {
			return array_replace( $en_built_in, $en_file_map );
		}

		return [];
	}

	/**
	 * Load phrase-level admin text overrides from dedicated language files.
	 */
	private static function load_admin_texts( string $lang_code ): array {
		static $cache = [];

		$lang_code = strtolower( $lang_code );

		if ( isset( $cache[ $lang_code ] ) ) {
			return $cache[ $lang_code ];
		}

		$file = __DIR__ . '/admin-texts/' . $lang_code . '.php';
		if ( is_readable( $file ) ) {
			$data = require $file;
			if ( is_array( $data ) ) {
				$cache[ $lang_code ] = $data;
				return $cache[ $lang_code ];
			}
		}

		$cache[ $lang_code ] = [];
		return $cache[ $lang_code ];
	}

	/**
	 * Returns value-level replacement map derived from admin_strings keys (SK value -> target value).
	 */
	public static function get_admin_strings_value_map( string $lang_code ): array {
		$all   = self::get_all();
		$sk    = $all['sk'] ?? null;
		$data  = $all[ $lang_code ] ?? null;
		$map   = [];

		if (
			! is_array( $sk )
			|| empty( $sk['admin_strings'] )
			|| ! is_array( $sk['admin_strings'] )
			|| ! is_array( $data )
			|| empty( $data['admin_strings'] )
			|| ! is_array( $data['admin_strings'] )
		) {
			return $map;
		}

		foreach ( $sk['admin_strings'] as $k => $sk_text ) {
			if ( ! isset( $data['admin_strings'][ $k ] ) ) {
				continue;
			}

			$source_text = (string) $sk_text;
			$target_text = (string) $data['admin_strings'][ $k ];
			if ( '' !== $source_text && $source_text !== $target_text ) {
				$map[ $source_text ] = $target_text;
			}
		}

		return $map;
	}

	/**
	 * Translate one admin UI text using built-in admin text maps.
	 */
	public static function translate_admin_text( string $lang_code, string $text ): string {
		if ( 'sk' === $lang_code ) {
			return $text;
		}

		$map = self::get_admin_text_map( $lang_code );
		if ( isset( $map[ $text ] ) ) {
			return $map[ $text ];
		}

		$value_map = self::get_admin_strings_value_map( $lang_code );
		return $value_map[ $text ] ?? $text;
	}
}
