<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return [
	'GTM šablóna' => 'GTM Template',
	'Import šablóny do Google Tag Managera' => 'Import Template into Google Tag Manager',
	'V tejto záložke si môžete stiahnuť pripravenú GTM šablónu pre Consent Mode a importovať ju do svojho kontajnera.' => 'In this tab you can download a ready-made GTM template for Consent Mode and import it into your container.',
	'Ak ešte nemáte dokončené základné nastavenia pluginu, najprv skontrolujte Consent Mode verziu a GTM Container ID v záložke Nastavenia.' => 'If you have not finished the basic plugin setup yet, first check the Consent Mode version and GTM Container ID in the Settings tab.',
	'Otvoriť nastavenia pluginu' => 'Open plugin settings',
	'Odporúčané pre väčšinu webov' => 'Recommended for most websites',
	'Šablóna pre štandardný Consent Mode v2. Obsahuje consent signály required pre Google Ads a GA4 v EÚ.' => 'Template for standard Consent Mode v2. Includes the required consent signals for Google Ads and GA4 in the EU.',
	'Stiahnuť šablónu v2' => 'Download v2 template',
	'Rozšírená verzia' => 'Advanced version',
	'Rozšírená šablóna s podporou ads_data_redaction, url_passthrough a developer_id pre pokročilé Google Marketing Platform scenáre.' => 'Advanced template with support for ads_data_redaction, url_passthrough, and developer_id for advanced Google Marketing Platform scenarios.',
	'Stiahnuť šablónu v3' => 'Download v3 template',
	'Postup importu' => 'Import steps',
	'Stiahnite si požadovanú verziu šablóny podľa toho, či používate Consent Mode v2 alebo v3.' => 'Download the template version you need depending on whether you use Consent Mode v2 or v3.',
	'V Google Tag Manageri otvorte Templates a v sekcii Tag Templates kliknite na New.' => 'In Google Tag Manager, open Templates and click New in the Tag Templates section.',
	'V menu vpravo hore zvoľte Import a vyberte stiahnutý .tpl súbor.' => 'In the top-right menu, choose Import and select the downloaded .tpl file.',
	'Po importe vytvorte nový tag z danej šablóny a doplňte polia podľa vašej implementácie.' => 'After import, create a new tag from the template and fill in the fields according to your implementation.',
	'Použite Preview režim, skontrolujte consent signály a potom publikujte kontajner.' => 'Use Preview mode, verify the consent signals, and then publish the container.',
	'Dôležité odporúčania po importe' => 'Important recommendations after import',
	'V plugine ponechajte rovnakú verziu Consent Mode, akú ste importovali do GTM.' => 'Keep the same Consent Mode version in the plugin that you imported into GTM.',
	'Ak načítavate GTM cez inú tému alebo plugin, pole GTM Container ID nechajte prázdne.' => 'If GTM is loaded by another theme or plugin, leave the GTM Container ID field empty.',
	'Pre Google Analytics skontrolujte analytics_storage, pre Google Ads najmä ad_storage, ad_user_data a ad_personalization.' => 'For Google Analytics, check analytics_storage; for Google Ads, especially ad_storage, ad_user_data, and ad_personalization.',
	'Overte správanie cez Google Tag Assistant a potvrďte, že sa tagy bez súhlasu nespúšťajú.' => 'Verify the behavior with Google Tag Assistant and confirm that tags do not fire without consent.',
	'Tip:' => 'Tip:',
	'Ak potrebujete len štandardnú implementáciu pre Google Ads a GA4, vo väčšine prípadov vám bude stačiť šablóna v2.' => 'If you only need a standard implementation for Google Ads and GA4, the v2 template will be enough in most cases.',
	'Jazyk podľa návštevníka' => 'Language by visitor',
	'Frontend cookie lišta sa pokúsi načítať jazyk návštevníka a zobraziť zodpovedajúci dostupný preklad.' => 'The frontend cookie banner will try to detect the visitor language and display the corresponding available translation.',
	'💡 Ak jazyk návštevníka nie je dostupný, plugin použije English (GB). Ak je voľba vypnutá, frontend používa aktuálne uložené texty bannera.' => '💡 If the visitor language is not available, the plugin uses English (GB). If this option is disabled, the frontend uses the currently saved banner texts.',
	'Pole ponúka detegované fonty z témy, theme.json, Elementora a frontend CSS. Môžete vybrať ponúknutý font alebo zadať vlastnú CSS font-family hodnotu.' => 'The field offers detected fonts from the theme, theme.json, Elementor, and frontend CSS. You can choose a suggested font or enter your own CSS font-family value.',
	'Pole ponúka iba detegované fonty z témy, theme.json, Elementora a frontend CSS.' => 'The field offers only detected fonts from the theme, theme.json, Elementor, and frontend CSS.',
	'Použiť font témy' => 'Use theme font',
	'Téma' => 'Theme',
	'Aktuálne uložené' => 'Currently saved',
	'Dátum a čas' => 'Date and time',
	'Súhlas nebol udelený.' => 'Consent has not been granted yet.',
	'💡 V zozname sa zobrazuje iba názov fontu. Po výbere sa uloží kompletná font-family hodnota detegovaná na stránke. Voľba "Použiť font témy" zodpovedá hodnote inherit.' => '💡 Only the font name is shown in the list. After selection, the full font-family value detected on the site is saved. The "Use theme font" option corresponds to the inherit value.',
	'Screenshoty postupu' => 'Step screenshots',
	'Náhľady obrazovky znázorňujú postup importu GTM šablóny a inštaláciu značky v Google Tag Manager.' => 'The screenshots illustrate the process of importing the GTM template and installing the tag in Google Tag Manager.',
	'Krok %d' => 'Step %d',
	'Screenshoty neboli nájdené.' => 'Screenshots were not found.',
	'Pridajte obrázky do admin/images a pomenujte ich napríklad template-screenshot-1.webp, template-screenshot-2.webp.' => 'Add images to admin/images and name them for example template-screenshot-1.webp, template-screenshot-2.webp.',
	'Predpripravené predvoľby' => 'Predefined presets',
	'Vyberte predvoľbu' => 'Select a preset',
	'Google Necessary' => 'Google Necessary',
	'Google Analytics' => 'Google Analytics',
	'Google Ads' => 'Google Ads',
	'Google Tag Manager' => 'Google Tag Manager',
	'Facebook Pixel' => 'Facebook Pixel',
	'Použiť predvoľbu' => 'Apply preset',
	'Predvoľby boli pridané.' => 'Presets were added.',
	'Všetky vybrané predvoľby už existujú.' => 'All selected presets already exist.',
	'Predpripravené sady cookies a skriptov' => 'Predefined cookie and script sets',
	'Hotové predvoľby jedným kliknutím doplnia bežné Google a Meta cookies spolu so súvisiacimi pravidlami blokovania.' => 'Ready-made presets add common Google and Meta cookies together with matching blocking rules in one click.',
	'Logo v banneri' => 'Banner logo',
	'Zobraziť logo v banneri' => 'Show logo in banner',
	'V pravom hornom rohu cookie lišty sa zobrazí vaše logo.' => 'Your logo will be displayed in the top-right corner of the cookie banner.',
	'Logo bannera' => 'Banner logo',
	'Nahrajte alebo vyberte logo z knižnice médií.' => 'Upload or select a logo from the media library.',
	'admin_banner_logo_desc' => 'Upload or select a logo from the media library.',
	'admin_banner_logo_formats_label' => 'Supported formats:',
	'admin_banner_logo_formats' => 'PNG, WebP',
	'admin_banner_logo_link_label' => 'Logo link URL',
	'admin_banner_logo_link_tip' => '💡 If you enter a URL, the logo will be clickable. Leave empty if you want it to be decorative only.',
	'URL na kliknutie loga' => 'Logo link URL',
	'💡 Ak zadáš URL, logo bude kliknuteľné. Nechaj prázdne, ak chceš aby bolo iba dekoratívne.' => '💡 If you enter a URL, the logo will be clickable. Leave empty if you want it to be decorative only.',
	'Podporované formáty: obrázky povolené vo WordPress (napr. JPG, JPEG, PNG, GIF, WebP). SVG iba ak je povolené vo WordPress.' => 'Supported formats: image types allowed by WordPress (e.g. JPG, JPEG, PNG, GIF, WebP). SVG only if enabled in WordPress.',
	'Nahrajte alebo vyberte obrázok z knižnice médií. Odporúčaná veľkosť: 50×50 px. Podporované formáty: obrázky povolené vo WordPress (napr. JPG, JPEG, PNG, GIF, WebP). SVG iba ak je povolené vo WordPress.' => 'Upload or select an image from the media library. Recommended size: 50×50 px. Supported formats: image types allowed by WordPress (e.g. JPG, JPEG, PNG, GIF, WebP). SVG only if enabled in WordPress.',
	'💡 Ikona sa zobrazí v kruhu s farbou pozadia (primárna farba). Pre najlepší výsledok použite biely alebo priehľadný obrázok 50×50 px.' => '💡 The icon is shown in a circle with background color (primary color). For best results, use a white or transparent 50×50 px image.',
	'Uložiť zmeny' => 'Save changes',
	'Šírka loga (px)' => 'Logo width (px)',
	'💡 Šírka loga v pixeloch (20–100 px). Výška sa prispôsobí automaticky.' => '💡 Logo width in pixels (20–100 px). Height adjusts automatically.',
	'↺ Obnoviť predvolené' => '↺ Restore defaults',
	'Obnoviť predvolenú farbu' => 'Restore default color',
];
